== The Lifecycles of Enterprise Beans

An enterprise bean goes through various stages during its lifetime, or
lifecycle. Each type of enterprise bean (stateful session, stateless
session, singleton session, or message-driven) has a different
lifecycle.

The descriptions that follow refer to methods that are explained along
with the code examples in the next two chapters. If you are new to
enterprise beans, you should skip this section and run the code
examples first.

=== The Lifecycle of a Stateful Session Bean

<<lifecycle-of-a-stateful-session-bean>> illustrates the stages that a
stateful session bean passes through during its lifetime. The client
initiates the lifecycle by obtaining a reference to a stateful session
bean. The container performs any dependency injection and then invokes
the method annotated with `@PostConstruct`, if any. The bean is now
ready to have its business methods invoked by the client.

[[lifecycle-of-a-stateful-session-bean]]
image::jakartaeett_dt_021.svg["Diagram showing the lifecycle of a stateful session bean.",title="Lifecycle of a Stateful Session Bean"]

While in the ready stage, the Enterprise Bean container may decide to
deactivate, or passivate, the bean by moving it from memory to
secondary storage. (Typically, the Enterprise Bean container uses a
least-recently-used algorithm to select a bean for passivation.) The
Enterprise Bean container invokes the method annotated `@PrePassivate`,
if any, immediately before passivating it. If a client invokes a
business method on the bean while it is in the passive stage, the
Enterprise Bean container activates the bean, calls the method
annotated `@PostActivate`, if any, and then moves it to the ready
stage.

At the end of the lifecycle, the client invokes a method annotated
`@Remove`, and the Enterprise Bean container calls the method annotated
`@PreDestroy`, if any. The bean's instance is then ready for garbage
collection.

Your code controls the invocation of only one lifecycle method: the
method annotated `@Remove`. All other methods in
<<lifecycle-of-a-stateful-session-bean>> are invoked by the Enterprise
Bean container. See
xref:resource-adapters-and-contracts[xrefstyle=full] for more
information.

=== The Lifecycle of a Stateless Session Bean

Because a stateless session bean is never passivated, its lifecycle has
only two stages: nonexistent and ready for the invocation of business
methods. <<lifecycle-of-a-stateless-or-singleton-session-bean>>
illustrates the stages of a stateless session bean.

[[lifecycle-of-a-stateless-or-singleton-session-bean]]
image::jakartaeett_dt_022.svg["Diagram showing the lifecycle of a stateless or singleton session bean.", title="Lifecycle of a Stateless or Singleton Session Bean"]

The Enterprise Bean container typically creates and maintains a pool of
stateless session beans, beginning the stateless session bean's
lifecycle. The container performs any dependency injection and then
invokes the method annotated `@PostConstruct`, if it exists. The bean
is now ready to have its business methods invoked by a client.

At the end of the lifecycle, the Enterprise Bean container calls the
method annotated `@PreDestroy`, if it exists. The bean's instance is
then ready for garbage collection.

=== The Lifecycle of a Singleton Session Bean

Like a stateless session bean, a singleton session bean is never
passivated and has only two stages, nonexistent and ready for the
invocation of business methods, as shown in
<<lifecycle-of-a-stateless-or-singleton-session-bean>>.

The Enterprise Bean container initiates the singleton session bean
lifecycle by creating the singleton instance. This occurs upon
application deployment if the singleton is annotated with the
`@Startup` annotation. The container performs any dependency injection
and then invokes the method annotated `@PostConstruct`, if it exists.
The singleton session bean is now ready to have its business methods
invoked by the client.

At the end of the lifecycle, the Enterprise Bean container calls the
method annotated `@PreDestroy`, if it exists. The singleton session
bean is now ready for garbage collection.

=== The Lifecycle of a Message-Driven Bean

<<lifecycle-of-a-message-driven-bean>> illustrates the stages in the
lifecycle of a message-driven bean.

[[lifecycle-of-a-message-driven-bean]]
image::jakartaeett_dt_023.svg["Diagram showing the lifecycle of a message-driven bean.",title="Lifecycle of a Message-Driven Bean"]

The Enterprise Bean container usually creates a pool of message-driven
bean instances. For each instance, the Enterprise Bean container
performs these tasks.

. If the message-driven bean uses dependency injection, the container
injects these references before instantiating the instance.
. The container calls the method annotated `@PostConstruct`, if any.

Like a stateless session bean, a message-driven bean is never
passivated and has only two states: nonexistent and ready to receive
messages.

At the end of the lifecycle, the container calls the method annotated
`@PreDestroy`, if any. The bean's instance is then ready for garbage
collection.
