== Sharing Information

Web components, like most objects, usually work with data to accomplish their tasks.
Web components can store this information in a database or in a scope object.

=== Using CDI Managed Beans

CDI can be used to define scope objects which can be injected in any container-managed objects such as web components.
These scope objects can then be used to store and transfer information.

CDI defines three basic scopes which can be used for this:

`@jakarta.enterprise.context.RequestScoped`::
In a servlet container, this is basically mapped to the `jakarta.servlet.ServletRequest`.
It lives from the time that the client has sent the request until it has retrieved the corresponding response.
It is not shared elsewhere.

`@jakarta.enterprise.context.SessionScoped`::
In a servlet container, this is basically mapped to the `jakarta.servlet.http.HttpSession`.
It lives for as long as the client is interacting with the web application with the same browser instance, and the session hasn't timed out at the server side.
It is shared among all requests in the same session.

`@jakarta.enterprise.context.ApplicationScoped`::
In a servlet container, this is basically mapped to the `jakarta.servlet.ServletContext`.
It lives for as long as the web application lives.
It is shared among all requests in all sessions.

The below example illustrates how the CDI `@SessionScoped` can be used to define an object which stores the user preferences.

[source,java]
----
@Named
@SessionScoped
public class UserPreferences implements Serializable {

    // TBD

}
----

[source,java]
----
@WebServlet("/foo")
public class Foo extends HttpServlet {

    @Inject
    private UserPreferences userPreferences;

    // TBD

}
----



















Collaborating web components share information by means of objects that are maintained as attributes of scope objects.
You access these attributes by using the `getAttribute` and `setAttribute` methods of the class representing the scope.
<<scope-objects>> lists the scope objects.

[[scope-objects]]
.Scope Objects
[width="90%",cols="15%,25%,50%"]
|===
|Scope Object |Class |Accessible From
|Application |`jakarta.servlet.ServletContext` |Web components within the web application.
See <<accessing-the-web-context>>.
|Session |`jakarta.servlet.http.HttpSession` |Web components handling a request that belongs to the session.
See <<maintaining-client-state>>.
|Request |`jakarta.servlet.ServletRequest` |Web components handling the request.
|===

=== Controlling Concurrent Access to Shared Resources

In a multithreaded server, shared resources can be accessed concurrently.
In addition to scope object attributes, shared resources include in-memory data, such as instance or class variables, and external objects, such as files, database connections, and network connections.

Concurrent access can arise in several situations.

* Multiple web components accessing objects stored in the web context.

* Multiple web components accessing objects stored in a session.

* Multiple threads within a web component accessing instance variables.

A web container will typically create a thread to handle each request.

When resources can be accessed concurrently, they can be used in an inconsistent fashion.
You prevent this by controlling the access using the synchronization techniques described in the Threads lesson at https://docs.oracle.com/javase/tutorial/essential/concurrency/[^].
