[[GKINL]][[using-ajax-functionality-with-javaserver-faces-technology]]

== Using Ajax Functionality with Jakarta Server Faces Technology

Ajax functionality can be added to a Jakarta Server Faces application in one
of the following ways:

* Adding the required JavaScript code to an application
* Using the built-in Ajax resource library

In earlier releases of the Jakarta EE platform, Jakarta Server Faces
applications provided Ajax functionality by adding the necessary
JavaScript to the web page. In the Jakarta EE platform, standard Ajax
support is provided by a built-in JavaScript resource library.

With the support of this JavaScript resource library, Jakarta Server Faces
standard UI components, such as buttons, labels, or text fields, can be
enabled for Ajax functionality. You can also load this resource library
and use its methods directly from within the managed bean code. The next
sections of the tutorial describe the use of the built-in Ajax resource
library.

In addition, because the Jakarta Server Faces technology component model can
be extended, custom components can be created with Ajax functionality.

The tutorial examples include an Ajax version of the `guessnumber`
application, `ajaxguessnumber`. See link:#GKOKB[The
ajaxguessnumber Example Application] for more information.

The Ajax specific `f:ajax` tag and its attributes are explained in the
next sections.


