== Overview of Jakarta XML Web Services

In Jakarta XML Web Services, a web service operation invocation is
represented by an XML-based protocol, such as SOAP. The SOAP
specification defines the envelope structure, encoding rules, and
conventions for representing web service invocations and responses.
These calls and responses are transmitted as SOAP messages (XML files)
over HTTP.

Although SOAP messages are complex, the XML Web Services API hides this
complexity from the application developer. On the server side, the
developer specifies the web service operations by defining methods in
an interface written in the Java programming language. The developer
also codes one or more classes that implement those methods. Client
programs are also easy to code. A client creates a proxy (a local
object representing the service) and then simply invokes methods on the
proxy. With XML Web Services, the developer does not generate or parse
SOAP messages. It is the XML Web Services runtime system that converts
the API calls and responses to and from SOAP messages.

With XML Web Services, clients and web services have a big advantage:
the platform independence of the Java programming language. In
addition, XML Web Services is not restrictive: A XML Web Services
client can access a web service that is not running on the Java
platform and vice versa. This flexibility is possible because XML Web
Services uses technologies defined by the W3C: HTTP, SOAP, and WSDL.
WSDL specifies an XML format for describing a service as a set of
endpoints operating on messages.

[NOTE]
Several files in the XML Web Services examples depend on the port that
you specified when you installed GlassFish Server. These tutorial
examples assume that the server runs on the default port, 8080. They do
not run with a nondefault port setting.
