== Introduction to Configuring Jakarta Faces Applications

The process of building and deploying simple Jakarta Faces applications is described in earlier chapters of this tutorial, including xref:getting-started-with-web-applications[xrefstyle=full], xref:introduction-to-facelets[xrefstyle=full], xref:using-ajax-with-jakarta-faces-technology[xrefstyle=full] and xref:composite-components-advanced-topics-and-an-example[xrefstyle=full] When you create large and complex applications, however, various additional configuration tasks are required.
These tasks include the following:

* Registering managed beans with the application so that all parts of the application have access to them

* Configuring managed beans and model beans so that they are instantiated with the proper values when a page makes reference to them

* Defining navigation rules for each of the pages in the application so that the application has a smooth page flow, if nondefault navigation is needed

* Packaging the application to include all the pages, resources, and other files so that the application can be deployed on any compliant container
