== Running the Duke's Bookstore Case Study Application

You can use either NetBeans IDE or Maven to build, package, deploy, and
run the Duke's Bookstore application.

=== To Build and Deploy Duke's Bookstore Using NetBeans IDE

. Make sure that GlassFish Server has been started (see
<<starting-and-stopping-glassfish-server>>).
. From the File menu, choose Open Project.
. In the Open Project dialog box, navigate to:
+
----
tut-install/examples/case-studies
----
. Select the `dukes-bookstore` folder.
. Click Open Project.
. In the Projects tab, right-click the `dukes-bookstore` project and
select Build.
+
This will build, package, and deploy Duke's Bookstore to GlassFish
Server.

=== To Build and Deploy Duke's Bookstore Using Maven

. Make sure that GlassFish Server has been started (see
<<starting-and-stopping-glassfish-server>>), as well as the database
server (see <<starting-and-stopping-apache-derby>>).
. In a terminal window, go to:
+
----
tut-install/examples/case-studies/dukes-bookstore/
----
. Enter the following command:
+
[source,shell]
----
mvn install
----
+
This command builds the application and packages it in a WAR file in
the `_tut-install_/examples/case-studies/dukes-bookstore/target/`
directory. It then deploys the application to GlassFish Server.

=== To Run Duke's Bookstore

. In a web browser, enter the following URL:
+
----
http://localhost:8080/dukes-bookstore/
----
. On the Duke's Bookstore main page, click a book in the graphic, or
click one of the links at the bottom of the page.
. Use the pages in the application to view and purchase books.
