[[GKNOJ]][[partial-processing-and-partial-rendering]]

== Partial Processing and Partial Rendering

The Jakarta Server Faces lifecycle spans all of the execute and render
processes of an application. It is also possible to process and render
only parts of an application, such as a single component. For example,
the Jakarta Server Faces Ajax framework can generate requests containing
information on which particular component may be processed and which
particular component may be rendered back to the client.

Once such a partial request enters the Jakarta Server Faces lifecycle, the
information is identified and processed by a
`jakarta.faces.context.PartialViewContext` object. The Jakarta Server Faces
lifecycle is still aware of such Ajax requests and modifies the
component tree accordingly.

The `execute` and `render` attributes of the `f:ajax` tag are used to
identify which components may be executed and rendered. For more
information on these attributes, see link:#GKIOW[Chapter 13,
"Using Ajax with Jakarta Server Faces Technology"].


