== User Interface Component Model

In addition to the lifecycle description, an overview of Jakarta Server
Faces architecture provides better understanding of the technology.

Jakarta Server Faces components are the building blocks of a Jakarta Server
Faces view. A component can be a user interface (UI) component or a
non-UI component.

Jakarta Server Faces UI components are configurable, reusable elements that
compose the user interfaces of Jakarta Server Faces applications. A
component can be simple, such as a button, or can be compound, such as a
table composed of multiple components.

Jakarta Server Faces technology provides a rich, flexible component
architecture that includes the following:

* A set of `jakarta.faces.component.UIComponent` classes for specifying
the state and behavior of UI components
* A rendering model that defines how to render the components in various
ways
* A conversion model that defines how to register data converters onto a
component
* An event and listener model that defines how to handle component
events
* A validation model that defines how to register validators onto a
component

This section briefly describes each of these pieces of the component
architecture.

=== User Interface Component Classes

Jakarta Server Faces technology provides a set of UI component classes and
associated behavioral interfaces that specify all the UI component
functionality, such as holding component state, maintaining a reference
to objects, and driving event handling and rendering for a set of
standard components.

The component classes are completely extensible, allowing component
writers to create their own custom components. See
xref:creating-custom-ui-components-and-other-custom-objects[xrefstyle=full]
for more information.

The abstract base class for all components is
`jakarta.faces.component.UIComponent`. Jakarta Server Faces UI component
classes extend the `UIComponentBase` class (a subclass of
`UIComponent`), which defines the default state and behavior of a
component. The following set of component classes is included with
Jakarta Server Faces technology.

* `UIColumn`: Represents a single column of data in a `UIData`
component.
* `UICommand`: Represents a control that fires actions when activated.
* `UIData`: Represents a data binding to a collection of data
represented by a `jakarta.faces.model.DataModel` instance.
* `UIForm`: Represents an input form to be presented to the user. Its
child components represent (among other things) the input fields to be
included when the form is submitted. This component is analogous to the
`form` tag in HTML.
* `UIGraphic`: Displays an image.
* `UIInput`: Takes data input from a user. This class is a subclass of
`UIOutput`.
* `UIMessage`: Displays a localized error message.
* `UIMessages`: Displays a set of localized error messages.
* `UIOutcomeTarget`: Displays a link in the form of a link or a button.
* `UIOutput`: Displays data output on a page.
* `UIPanel`: Manages the layout of its child components.
* `UIParameter`: Represents substitution parameters.
* `UISelectBoolean`: Allows a user to set a `boolean` value on a control
by selecting or deselecting it. This class is a subclass of the
`UIInput` class.
* `UISelectItem`: Represents a single item in a set of items.
* `UISelectItems`: Represents an entire set of items.
* `UISelectMany`: Allows a user to select multiple items from a group of
items. This class is a subclass of the `UIInput` class.
* `UISelectOne`: Allows a user to select one item from a group of items.
This class is a subclass of the `UIInput` class.
* `UIViewParameter`: Represents the query parameters in a request. This
class is a subclass of the `UIInput` class.
* `UIViewRoot`: Represents the root of the component tree.

In addition to extending `UIComponentBase`, the component classes also
implement one or more behavioral interfaces, each of which defines
certain behavior for a set of components whose classes implement the
interface.

These behavioral interfaces, all defined in the `jakarta.faces.component`
package unless otherwise stated, are as follows.

* `ActionSource`: Indicates that the component can fire an action event.
This interface is intended for use with components based on Jakarta Server
Faces technology 1.1_01 and earlier versions. This interface is
deprecated in Jakarta Server Faces 2.
* `ActionSource2`: Extends `ActionSource` and therefore provides the
same functionality. However, it allows components to use the Expression
Language (EL) when they are referencing methods that handle action
events.
* `EditableValueHolder`: Extends `ValueHolder` and specifies additional
features for editable components, such as validation and emitting
value-change events.
* `NamingContainer`: Mandates that each component rooted at this
component have a unique ID.
* `StateHolder`: Denotes that a component has state that must be saved
between requests.
* `ValueHolder`: Indicates that the component maintains a local value as
well as the option of accessing data in the model tier.
* `jakarta.faces.event.SystemEventListenerHolder`: Maintains a list of
`jakarta.faces.event.SystemEventListener` instances for each type of
`jakarta.faces.event.SystemEvent` defined by that class.
* `jakarta.faces.component.behavior.ClientBehaviorHolder`: Adds the
ability to attach `jakarta.faces.component.behavior.ClientBehavior`
instances, such as a reusable script.

`UICommand` implements `ActionSource2` and `StateHolder`. `UIOutput` and
component classes that extend `UIOutput` implement `StateHolder` and
`ValueHolder`. `UIInput` and component classes that extend `UIInput`
implement `EditableValueHolder`, `StateHolder`, and `ValueHolder`.
`UIComponentBase` implements `StateHolder`.

Only component writers will need to use the component classes and
behavioral interfaces directly. Page authors and application developers
will use a standard component by including a tag that represents it on a
page. Most of the components can be rendered in different ways on a
page. For example, a `UICommand` component can be rendered as a button
or a link.

The next section explains how the rendering model works and how page
authors can choose to render the components by selecting the appropriate
tags.

=== Component Rendering Model

The Jakarta Server Faces component architecture is designed such that the
functionality of the components is defined by the component classes,
whereas the component rendering can be defined by a separate renderer
class. This design has several benefits, including the following.

* Component writers can define the behavior of a component once but
create multiple renderers, each of which defines a different way to
render the component to the same client or to different clients.
* Page authors and application developers can change the appearance of a
component on the page by selecting the tag that represents the
appropriate combination of component and renderer.

A render kit defines how component classes map to component tags that
are appropriate for a particular client. The Jakarta Server Faces
implementation includes a standard HTML render kit for rendering to an
HTML client.

The render kit defines a set of `jakarta.faces.render.Renderer` classes
for each component that it supports. Each `Renderer` class defines a
different way to render the particular component to the output defined
by the render kit. For example, a `UISelectOne` component has three
different renderers. One of them renders the component as a group of
options. Another renders the component as a combo box. The third one
renders the component as a list box. Similarly, a `UICommand` component
can be rendered as a button or a link, using the `h:commandButton` or
`h:commandLink` tag. The `command` part of each tag corresponds to the
`UICommand` class, specifying the functionality, which is to fire an
action. The `Button` or `Link` part of each tag corresponds to a
separate `Renderer` class that defines how the component appears on the
page.

Each custom tag defined in the standard HTML render kit is composed of
the component functionality (defined in the `UIComponent` class) and the
rendering attributes (defined by the `Renderer` class).

The section
<<adding-components-to-a-page-using-html-tag-library-tags>> lists all
supported component tags and illustrates how to use the tags in an
example.

The Jakarta Server Faces implementation provides a custom tag library for
rendering components in HTML.

=== Conversion Model

A Jakarta Server Faces application can optionally associate a component
with server-side object data. This object is a JavaBeans component,
such as a managed bean. An application gets and sets the object data
for a component by calling the appropriate object properties for that
component.

When a component is bound to an object, the application has two views
of the component's data.

* The model view, in which data is represented as data types, such as
`int` or `long`.
* The presentation view, in which data is represented in a manner that
can be read or modified by the user. For example, a `java.util.Date`
might be represented as a text string in the format `mm/dd/yy` or as a
set of three text strings.

The Jakarta Server Faces implementation automatically converts
component data between these two views when the bean property
associated with the component is of one of the types supported by the
component's data. For example, if a `UISelectBoolean` component is
associated with a bean property of type `java.lang.Boolean`, the
Jakarta Server Faces implementation will automatically convert the
component's data from `String` to `Boolean`. In addition, some
component data must be bound to properties of a particular type. For
example, a `UISelectBoolean` component must be bound to a property of
type `boolean` or `java.lang.Boolean`.

Sometimes you might want to convert a component's data to a type other
than a standard type, or you might want to convert the format of the
data. To facilitate this, Jakarta Server Faces technology allows you to
register a `jakarta.faces.convert.Converter` implementation on
`UIOutput` components and components whose classes subclass `UIOutput`.
If you register the `Converter` implementation on a component, the
`Converter` implementation converts the component's data between the
two views.

You can either use the standard converters supplied with the Jakarta
Server Faces implementation or create your own custom converter. Custom
converter creation is covered in
xref:creating-custom-ui-components-and-other-custom-objects[xrefstyle=full].

=== Event and Listener Model

The Jakarta Server Faces event and listener model is similar to the
JavaBeans event model in that it has strongly typed event classes and
listener interfaces that an application can use to handle events
generated by components.

The Jakarta Server Faces specification defines three types of events:
application events, system events, and data-model events.

Application events are tied to a particular application and are
generated by a `UIComponent`. They represent the standard events
available in previous versions of Jakarta Server Faces technology.

An event object identifies the component that generated the event and
stores information about the event. To be notified of an event, an
application must provide an implementation of the listener class and
must register it on the component that generates the event. When the
user activates a component, such as by clicking a button, an event is
fired. This causes the Jakarta Server Faces implementation to invoke the
listener method that processes the event.

Jakarta Server Faces supports two kinds of application events: action events
and value-change events.

An action event (class `jakarta.faces.event.ActionEvent`) occurs when the
user activates a component that implements `ActionSource`. These
components include buttons and links.

A value-change event (class `jakarta.faces.event.ValueChangeEvent`) occurs
when the user changes the value of a component represented by `UIInput`
or one of its subclasses. An example is selecting a check box, an action
that results in the component's value changing to `true`. The component
types that can generate these types of events are the `UIInput`,
`UISelectOne`, `UISelectMany`, and `UISelectBoolean` components.
Value-change events are fired only if no validation errors are detected.

Depending on the value of the `immediate` property (see
<<the-immediate-attribute>>) of the component emitting the event,
action events can be processed during the Invoke Application phase or
the Apply Request Values phase, and value-change events can be
processed during the Process Validations phase or the Apply Request
Values phase.

System events are generated by an `Object` rather than a `UIComponent`.
They are generated during the execution of an application at predefined
times. They are applicable to the entire application rather than to a
specific component.

A data-model event occurs when a new row of a `UIData` component is
selected.

There are two ways to cause your application to react to action events
or value-change events that are emitted by a standard component:

* Implement an event listener class to handle the event, and register
the listener on the component by nesting either an
`f:valueChangeListener` tag or an `f:actionListener` tag inside the
component tag.
* Implement a method of a managed bean to handle the event, and refer to
the method with a method expression from the appropriate attribute of
the component's tag.

See <<implementing-an-event-listener>> for information on how to
implement an event listener. See
<<registering-listeners-on-components>> for information on how to
register the listener on a component.

See <<writing-a-method-to-handle-an-action-event>> and
<<writing-a-method-to-handle-a-value-change-event>> for information on
how to implement managed bean methods that handle these events.

See <<referencing-a-managed-bean-method>> for information on how to
refer to the managed bean method from the component tag.

When emitting events from custom components, you must implement the
appropriate event class and manually queue the event on the component
in addition to implementing an event listener class or a managed bean
method that handles the event.
<<handling-events-for-custom-components>> explains how to do this.

=== Validation Model

Jakarta Server Faces technology supports a mechanism for validating the
local data of editable components (such as text fields). This
validation occurs before the corresponding model data is updated to
match the local value.

Like the conversion model, the validation model defines a set of
standard classes for performing common data validation checks. The
Jakarta Server Faces core tag library also defines a set of tags that
correspond to the standard `jakarta.faces.validator.Validator`
implementations. See <<using-the-standard-validators>> for a list of
all the standard validation classes and corresponding tags.

Most of the tags have a set of attributes for configuring the
validator's properties, such as the minimum and maximum allowable
values for the component's data. The page author registers the
validator on a component by nesting the validator's tag within the
component's tag.

In addition to validators that are registered on the component, you can
declare a default validator that is registered on all `UIInput`
components in the application. For more information on default
validators, see <<using-default-validators>>.

The validation model also allows you to create your own custom
validator and corresponding tag to perform custom validation. The
validation model provides two ways to implement custom validation.

* Implement a `Validator` interface that performs the validation.
* Implement a managed bean method that performs the validation.

If you are implementing a `Validator` interface, you must also do the
following.

* Register the `Validator` implementation with the application.
* Create a custom tag or use an `f:validator` tag to register the
validator on the component.

In the previously described standard validation model, the validator is
defined for each input component on a page. The Bean Validation model
allows the validator to be applied to all fields in a page. See
xref:introduction-to-jakarta-bean-validation[xrefstyle=full] and
xref:bean-validation-advanced-topics[xrefstyle=full] for more
information on Bean Validation.
