== Introduction to Configuring Jakarta Faces Applications

The process of building and deploying simple Jakarta Faces applications is described in earlier chapters of this tutorial, including xref:webapp/webapp.adoc#_getting_started_with_web_applications[Getting Started with Web Applications], xref:faces-facelets/faces-facelets.adoc#_introduction_to_facelets[Introduction to Facelets], xref:faces-ajax/faces-ajax.adoc#_using_ajax_with_jakarta_faces_technology[Using Ajax with Jakarta Faces Technology] and xref:faces-advanced-cc/faces-advanced-cc.adoc#_composite_components_advanced_topics_and_an_example[Composite Components: Advanced Topics and an Example] When you create large and complex applications, however, various additional configuration tasks are required.
These tasks include the following:

* Registering managed beans with the application so that all parts of the application have access to them

* Configuring managed beans and model beans so that they are instantiated with the proper values when a page makes reference to them

* Defining navigation rules for each of the pages in the application so that the application has a smooth page flow, if nondefault navigation is needed

* Packaging the application to include all the pages, resources, and other files so that the application can be deployed on any compliant container
