[[GEXAJ]][[required-software]]

== Required Software

The following software is required to run the examples:

* link:#java-platform-standard-edition[Java Platform, Standard Edition]
* link:#eclipse-glassfish[Eclipse GlassFish]
* link:#eclipse-glassfish-installation-tips[GlassFish Server Installation Tips]
* link:#jakarta-ee-8-tutorial-examples[Jakarta EE 8 Tutorial Component]
* link:#netbeans-ide[NetBeans IDE]
* link:#apache-maven[Apache Maven]

[[GEXAE]][[java-platform-standard-edition]]

=== Java Platform, Standard Edition

To build, deploy, and run the examples, you need a copy of the Java
Platform, Standard Edition Development Kit (JDK). You must use JDK 7
Update 65 or above or JDK 8 Update 20 or above. You can download JDK
software from
`http://www.oracle.com/technetwork/java/javase/downloads/index.html`.

[[GEXAB]][[eclipse-glassfish]]

=== Eclipse GlassFish

Eclipse GlassFish Server 5.1 is targeted as the build and
runtime environment for the tutorial examples. To build, deploy, and run
the examples, you need a copy of GlassFish Server and, optionally,
NetBeans IDE. You can download Eclipse GlassFish Server from
`https://eclipse-ee4j.github.io/glassfish/download`.


[[GEXBC]][[eclipse-glassfish-installation-tips]]

==== Eclipse GlassFish Server Installation Tips

GlassFish Server is installed from a ZIP file. It sets the
default administration user name as `admin` with no required password.
The Admin Port is set to 4848, and the HTTP Port is set to 8080.

This tutorial refers to `_as-install-parent_`, the directory where you
install GlassFish Server. For example, the default installation
directory on Microsoft Windows is `C:\glassfish5`, so `_as-install-parent_`
is `C:\glassfish5`. GlassFish Server itself is installed in `_as-install_`,
the `glassfish` directory under `_as-install-parent_`. So on Microsoft
Windows, `_as-install_` is `C:\glassfish5\glassfish`.

After you install GlassFish Server, add the following directories to
your `PATH` to avoid having to specify the full path when you use
commands:

[source,java]
----
as-install-parent/bin
as-install/bin
----

[[GEXBA]][[jakarta-ee-8-tutorial-component]]

=== Jakarta EE 8 Tutorial Component

The tutorial component, including the documentation and example source,
is contained in GlassFish Server.

////
Updates to the Jakarta EE Tutorial are published periodically. For
details on obtaining these updates, see
link:#GIQWR[Getting the Latest Updates to the
Tutorial].
////

[[GEXAZ]][[netbeans-ide]]

=== Apache NetBeans IDE

The Apache NetBeans integrated development environment (IDE) is a free,
open-source IDE for developing Java applications, including enterprise
applications. Apache NetBeans IDE supports the Jakarta EE platform. You can build,
package, deploy, and run the tutorial examples from within Apache NetBeans IDE.

To run the tutorial examples, you need the latest version of Apache NetBeans
IDE. You can download Apache NetBeans IDE from
`https://netbeans.apache.org/downloads/index.html`. Make sure that you download
the Jakarta EE bundle.

[[GJSEQ]][[to-install-apache-netbeans-ide-without-glassfish-server]]

==== To Install Apache NetBeans IDE without GlassFish Server

When you install Apache NetBeans IDE, do not install the version of GlassFish
Server that comes with Apache NetBeans IDE. To skip the installation of
GlassFish Server, follow these steps.

1.  On the first page of the NetBeans IDE Installer wizard, deselect the
check box for Eclipse GlassFish Server and click OK.
2.  Accept both the License Agreement and the Junit License Agreement.
+
A few of the tutorial examples use the Junit library, so you should
install it.
3.  Continue with the installation of NetBeans IDE.

[[GIQZL]][[to-add-eclipse-glassfish-server-as-a-server-using-apache-netbeans-ide]]

==== To Add Eclipse GlassFish Server as a Server Using Apache NetBeans IDE

To run the tutorial examples in Apache NetBeans IDE, you must add your
Eclipse GlassFish Server as a server in NetBeans IDE. Follow these instructions
to add GlassFish Server to NetBeans IDE.

1.  From the Tools menu, choose Servers.
2.  In the Servers wizard, click Add Server.
3.  Under Choose Server, select GlassFish Server and click Next.
4.  Under Server Location, browse to the Eclipse GlassFish Server installation
and click Next.
5.  Under Domain Location, select Register Local Domain.
6.  Click Finish.

[[GEXAA]][[apache-maven]]

=== Apache Maven

Maven is a Java technology-based build tool developed by the Apache
Software Foundation and is used to build, package, and deploy the
tutorial examples. To run the tutorial examples from the command line,
you need Maven 3.0 or higher. If you do not already have Maven, you can
install it from:

`http://maven.apache.org`

Be sure to add the maven-install`/bin` directory to your path.

If you are using Apache NetBeans IDE to build and run the examples, it includes
a copy of Maven.
