[[BNADI]][[starting-and-stopping-eclipse-glassfish-server]]

== Starting and Stopping Eclipse GlassFish Server

You can start and stop Eclipse GlassFish Server using either Apache NetBeans IDE or the
command line.

[[CHDCACDI]][[to-start-eclipse-glassfish-server-using-apache-netbeans-ide]]

=== To Start Eclipse GlassFish Server Using Apache NetBeans IDE

1.  Click the Services tab.
2.  Expand Servers.
3.  Right-click the GlassFish Server instance and select Start.

[[sthref14]][[to-stop-eclipse-glassfish-server-using-apache-netbeans-ide]]

=== To Stop Eclipse GlassFish Server Using Apache NetBeans IDE

To stop Eclipse GlassFish Server using Apache NetBeans IDE, right-click the GlassFish
Server instance and select Stop.

[[CHDBDDAF]][[to-start-eclipse-glassfish-server-using-the-command-line]]

=== To Start Eclipse GlassFish Server Using the Command Line

To start Eclipse GlassFish Server from the command line, open a terminal window
or command prompt and execute the following:

[source,java]
----
asadmin start-domain --verbose
----

A domain is a set of one or more Eclipse GlassFish Server instances managed by
one administration server. The following elements are associated with a
domain:

* The Eclipse GlassFish Server port number: The default is 8080.
* The administration server's port number: The default is 4848.
* An administration user name and password: The default user name is
`admin`, and by default no password is required.

You specify these values when you install Eclipse GlassFish Server. The examples
in this tutorial assume that you chose the default ports as well as the
default user name and lack of password.

With no arguments, the `start-domain` command initiates the default
domain, which is `domain1`. The `--verbose` flag causes all logging and
debugging output to appear on the terminal window or command prompt. The
output also goes into the server log, which is located in
domain-dir`/logs/server.log`.

[[sthref15]][[to-stop-eclipse-glassfish-server-using-the-command-line]]

=== To Stop Eclipse GlassFish Server Using the Command Line

To stop Eclipse GlassFish Server, open a terminal window or command prompt and
execute:

[source,java]
----
asadmin stop-domain domain1
----


