== Jakarta EE Maven Archetypes in the Tutorial

Some of the chapters have instructions on how to build an example
application using Maven archetypes. Archetypes are templates for
generating a particular Maven project. The Tutorial includes several
Maven archetypes for generating Jakarta EE projects.

=== Installing the Tutorial Archetypes

You must install the included Maven archetypes into your local Maven
repository before you can create new projects based on the archetypes.
You can install the archetypes using NetBeans IDE or Maven.

==== Installing the Tutorial Archetypes Using NetBeans IDE

1. From the *File* menu, choose *Open Project*.
2. In the Open Project dialog box, navigate to: 
+
```
tut-install/examples
```
3. Select the `archetypes` folder.
4. Click *Open Project*.
5. In the *Projects* tab, right-click the `archetypes` project and
select *Build*.

==== Installing the Tutorial Archetypes Using Maven

1.  In a terminal window, go to: 
+
```
tut-install/examples/archetypes/
```
2.  Enter the following command: 
+
```
mvn install
```
