////
[NOTE]
Glassfish no longer ships with Update Tool
////
////
== Getting the Latest Updates to the Tutorial

Check for any updates to the tutorial by using the Update Tool included with the Jakarta EE SDK.

=== To Update the Tutorial Using NetBeans IDE

. Open the *Services* tab in NetBeans IDE and expand *Servers*.

. Right-click the GlassFish Server instance and select *View Domain Update Center* to display the Update Tool.

. Select *Available Updates* in the tree to display a list of updated packages.

. Look for updates to the Jakarta EE Tutorial (jakartaee-tutorial) package.

. If there is an updated version of the Tutorial, select *Jakarta EE Tutorial* (`jakartaee-tutorial`) and click *Install*.

=== To Update the Tutorial Using the Command Line

. Open a terminal window and enter the following command to display the Update Tool: +
----
updatetool
----

. Select *Available Updates* in the tree to display a list of updated packages.

. Look for updates to the Jakarta EE Tutorial (`jakartaee-tutorial`) package.

. If there is an updated version of the tutorial, select *Jakarta EE Tutorial* (`jakartaee-tutorial`) and click *Install*.

////