== Transactions in Jakarta EE Applications

In a Jakarta EE application, a transaction is a series of actions that
must all complete successfully, or else all the changes in each action
are backed out. Transactions end in either a commit or a rollback.

Jakarta Transactions allows applications to access transactions in a
manner that is independent of specific implementations. Jakarta
Transactions specifies standard Java interfaces between a transaction
manager and the parties involved in a distributed transaction system:
the transactional application, the Jakarta EE server, and the manager
that controls access to the shared resources affected by the
transactions.

Jakarta Transactions defines the `UserTransaction` interface that
applications use to start, commit, or roll back transactions.
Application components get a `UserTransaction` object through a JNDI
lookup by using the name `java:comp/UserTransaction` or by requesting
injection of a `UserTransaction` object. An application server uses a
number of Jakarta Transactions defined interfaces to communicate with a
transaction manager; a transaction manager uses Jakarta Transactions
defined interfaces to interact with a resource manager.

The Jakarta Transactions 2.0 specification is available at
https://jakarta.ee/specifications/transactions/2.0/[^].
