== Hello World Web Application Using Jakarta Faces

The `hello-faces` application is a web application that uses Jakarta Faces take a name as an HTTP request parameter, generate the greeting and return it as an HTTP response.
As a presentation-oriented web application, the response is represented as a HTML document.

The source code for this application is in the `_jakartaee-examples_/tutorial/web/faces/hello-faces/` directory.

Jakarta Faces is a component-based MVC framework that provides its own servlet as controller (the "C" part of MVC), the `FacesServlet`.
The model and the view are usually provided by you, the web developer.

=== The Model

In a typical Jakarta Faces application, the model (the "M" part of MVC) is represented by a bean class.
Such a bean class is in the Jakarta Faces world called a _Backing Bean_.

For this Hello World web application, the `src/main/java/jakarta/tutorial/web/faces/Hello.java` backing bean defines a `name` property along with a getter and setter, a `greeting` property along with a getter, and a `submit` action method which creates the `greeting` as output-based on `name` as input.

[source,java]
----
package jakarta.tutorial.web.faces;

import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Named;

@Named
@RequestScoped
public class Hello {

    private String name;
    private String greeting;

    public void submit() {
        greeting = "Hello, " + name + "!";
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String getGreeting() {
        return greeting;
    }
}
----

Note that a getter is required for output and that a setter is only required for input.

In a typical Jakarta Faces application, CDI is used to manage the backing beans.
We'll briefly go through the CDI annotations that are used here:

* `@Named` -- gives the backing bean a managed bean name, which is primarily used to reference it in Expression Language (EL).
  Without any attributes this defaults to the simple class name with the first letter in lowercase.
  This backing bean will thus be available as a managed bean via `&#35;\{hello}` in EL.
* `@RequestScoped` -- gives the backing bean a managed bean scope, which essentially represents its lifespan.
  In this case that lifespan is the duration of an HTTP request.
  When the HTTP request ends, then the managed bean instance is destroyed.

=== The View

In a typical Jakarta Faces application, the view (the "V" part of MVC) is represented by a XHTML file.
Such a XHTML file is in the Jakarta Faces world called a _Facelets File_ or just _Facelet_.
In Jakarta Faces, the view technology is pluggable and Facelets is used as the default view technology.
XHTML markup is being used because it allows the framework to easily use a XML parser to find Jakarta Faces tags of interest and to generate HTML output.

For this Hello World web application, the `src/main/webapp/hello.xhtml` Facelet defines a form with an input field, a command button and an output field.

[source,xml]
----
<!DOCTYPE html>
<html lang="en"
      xmlns:f="jakarta.faces.core"
      xmlns:h="jakarta.faces.html">
    <h:head>
        <title>Jakarta Faces Hello World</title>
    </h:head>
    <h:body>
        <h1>Hello, what's your name?</h1>
        <h:form>
            <h:inputText value="#{hello.name}" required="true" />
            <h:commandButton value="Submit" action="#{hello.submit}">
                <f:ajax execute="@form" render=":greeting" />
            </h:commandButton>
            <h:messages />
        </h:form>
        <h:outputText id="greeting" value="#{hello.greeting}" />
    </h:body>
</html>
----

We'll briefly go through the Jakarta Faces-specific XHTML tags that are used here.

* `<h:head>` -- generates the HTML `<head>`.
  It gives Jakarta Faces the opportunity to automatically include any necessary JS and CSS files in the generated HTML head.
* `<h:body>` -- generates the HTML `<body>`.
  It gives Jakarta Faces the opportunity to automatically include any necessary JS files in the end of the generated HTML body.
* `<h:form>` -- generates the HTML `<form>`.
  It gives Jakarta Faces the opportunity to automatically include a hidden field representing the view state.
* `<h:inputText>` -- generates the HTML `<input>`.
  It gives Jakarta Faces the opportunity to automatically get and set the value as a managed bean property specified in the `value` attribute, as well as to perform any conversion and validation on it.
* `<h:commandButton>` -- generates the HTML `<input type="submit">`.
  It gives Jakarta Faces the opportunity to automatically invoke the backing bean method specified in the `action` attribute.
* `<h:messages>` -- generates the HTML `<ul>` or `<div>` or `<table>` depending on state and configuration.
  It gives you the opportunity to declare the place where any conversion and validation messages will be displayed.
* `<f:ajax>` -- generates the necessary JavaScript code for Ajax behavior.
  If gives you the opportunity to configure the form submit to be performed asynchronously using Ajax.
* `<h:outputText>` -- generates the HTML `<span>`.
  This is the one being updated on completion of the Ajax submit and it will display the current value of the managed bean property specified in the `value` attribute.

The `<h:...>` tags define standard HTML components.
The `<f:...>` tags define behavior.

The input value is via EL value expression `&#35;{hello.name}` connected to the `name` property of the `Hello` backing bean via its getter and setter.
The output value is via EL value expression `&#35;{hello.greeting}` connected to the `greeting` property of the `Hello` backing bean via its getter.
The command button is via EL method expression `&#35;{hello.submit}` connected to the `submit` method of the `Hello` backing bean.

Note that for EL value expressions the physical field representing the property doesn't need to have exactly the same name nor that it needs to exist at all.
EL only looks for the getter and setter methods, not for the field.

=== The Controller

In a typical Jakarta Faces application, the controller (the "C" part of MVC) is registered in the Jakarta Servlet deployment descriptor file, the `src/main/webapp/WEB-INF/web.xml`.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd"
         version="6.0">
    <servlet>
        <servlet-name>facesServlet</servlet-name>
        <servlet-class>jakarta.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>facesServlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>
</web-app>
----

It basically instructs the servlet container to create an instance of `jakarta.faces.webapp.FacesServlet` as `facesServlet` during startup and to execute it when the URL pattern of the HTTP request matches `*.xhtml`.

=== Running the `hello-faces` example application

Build and deploy as instructed in xref:webapp/webapp.adoc#_building_deploying_and_running_the_example_projects[Building, Deploying and Running The Example Projects].

In a web browser, open the following URL:

----
http://localhost:8080/hello-faces/hello.xhtml
----

It will show a web page with a form asking for your name.
Enter your name in the input field of the form, for example 'Duke', and click Submit.
This will show the text `Hello, Duke!` below the form.
