[[BNBXE]][[securing-containers]]

== Securing Containers

In Jakarta EE, the component containers are responsible for providing
application security. A container provides two types of security:
declarative and programmatic.

[[BNBXG]][[using-annotations-to-specify-security-information]]

=== Using Annotations to Specify Security Information

Annotations enable a declarative style of programming and so encompass
both the declarative and programmatic security concepts. Users can
specify information about security within a class file by using
annotations. GlassFish Server uses this information when the application
is deployed. Not all security information can be specified by using
annotations, however. Some information must be specified in the
application deployment descriptors.

Specific annotations that can be used to specify security information
within an enterprise bean class file are described in
link:#GJGDI[Securing an Enterprise Bean Using
Declarative Security]. link:#BNCAS[Chapter 51,
"Getting Started Securing Web Applications"], describes how to use
annotations to secure web applications where possible. Deployment
descriptors are described only where necessary.

For more information on annotations, see
link:#BNBYJ[Further Information about Security].

[[BNBXF]][[using-deployment-descriptors-for-declarative-security]]

=== Using Deployment Descriptors for Declarative Security

Declarative security can express an application component's security
requirements by using deployment descriptors. Because deployment
descriptor information is declarative, it can be changed without the
need to modify the source code. At runtime, the Jakarta EE server reads the
deployment descriptor and acts upon the corresponding application,
module, or component accordingly. Deployment descriptors must provide
certain structural information for each component if this information
has not been provided in annotations or is not to be defaulted.

This part of the tutorial does not document how to create deployment
descriptors; it describes only the elements of the deployment descriptor
relevant to security. NetBeans IDE provides tools for creating and
modifying deployment descriptors.

Different types of components use different formats, or schemas, for
their deployment descriptors. The security elements of deployment
descriptors discussed in this tutorial include the following.

* Web components may use a web application deployment descriptor named
`web.xml`.
+
The schema for web component deployment descriptors is provided in
Chapter 14 of the Jakarta Servlet 4.0 specification, which can be
downloaded from `https://jakarta.ee/specifications/servlet/4.0/`.
* Jakarta Enterprise Beans components may use an enterprise bean deployment descriptor
named `META-INF/ejb-jar.xml`, contained in the enterprise bean JAR file.
+
The schema for enterprise bean deployment descriptors is provided in
Chapter 14 of the Jakarta Enterprise Beans 3.2 Core Contracts and Requirements Specification,
which can be downloaded from
`https://jakarta.ee/specifications/enterprise-beans/3.2/`.

[[BNBXH]][[using-programmatic-security]]

=== Using Programmatic Security

Programmatic security is embedded in an application and is used to make
security decisions. Programmatic security is useful when declarative
security alone is not sufficient to express the security model of an
application. The API for programmatic security consists of methods of the Jakarta
Security `SecurityContext` interface, and methods of the enterprise bean `EJBContext`
interface and the servlet `HttpServletRequest` interface. These
methods allow components to make business-logic decisions based on the
security role of the caller or remote user.

Programmatic security is discussed in more detail in the following
sections:

* link:#GJIIE[Using Programmatic Security with
Web Applications]
* link:#GJGCS[Securing an Enterprise Bean
Programmatically]
