[preface]

= Preface

include::ROOT:partial$draft.adoc[]

== Legal

This documentation and the accompanying materials are made available under the terms of the Eclipse Public License v. 2.0,
which is available at https://www.eclipse.org/legal/epl-2.0.

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its affiliates. Other names may be trademarks of their respective owners.

== About this Tutorial

This tutorial explains how to use the features of the Jakarta EE Platform to build cloud-native applications,
such as microservices, "right sized" services, and server-based web applications.

== Prerequisites

Jakarta EE applications use the Java Platform, and are usually written in the Java programming language.
All the examples in this tutorial are written in Java.
If you're new to Java, spend some time getting up to speed on the language and platform;
a good place to start is https://dev.java/learn/[dev.java/learn].

Each topic in this tutorial provides some background information,
but in general,
we assume you have a basic understanding of the technologies each Jakarta EE feature works with.
For example, in the Jakarta Persistence chapter,
we assume you have a basic understanding of relational databases.

== Conventions

Throughout this tutorial, we use the following typographic conventions:

[width="99%",cols="20%,38%,37%"]
|===
|Convention |Meaning |Example

|*Boldface* |Boldface type indicates graphical user interface elements associated with an action or terms defined in text. |From the *File* menu, choose *Open Project*.

A *cache* is a copy stored locally.

|`Monospace` |Monospace type indicates the names of files and directories, commands within a paragraph, URLs, code in examples, text that appears on the screen, or text that you enter. |Edit your `.login` file.

Use `ls -a` to list all files.

`_machine_name_% you have mail.`

|_Italic_ |Italic type indicates book titles, emphasis, or placeholder variables for which you supply particular values. |Read Chapter 6 in the _User's Guide_.

_Don’t_ save the file.

The command to remove a file is `rm _filename_`.
|===

== Default Paths and File Names

The following table describes the default paths and file names that are
used in this book.

[width="99%",cols="20%,38%,38%"]
|===
|Placeholder |Description |Default Value

|`_as-install_` |Represents the base installation directory for GlassFish Server. | Installations on the Linux, UNIX, or macOS:

`_user's-home-directory_/glassfish6/glassfish`

Windows, all installations:

`_SystemDrive_:\glassfish6\glassfish`

|`_as-install-parent_` |Represents the parent of the base installation directory for GlassFish Server. |Installations on UNIX/Linux/macOS:

`_user's-home-directory_/glassfish6`

Windows:

`_SystemDrive_:\glassfish6`

|`_jakartaee-examples_` |Represents the base installation directory for the Jakarta EE Tutorial examples project after you download or clone it. |`_user's-home-directory_/jakartaee-examples`

|`_domain-dir_` |Represents the directory in which a domain's configuration is stored. |`_as-install_/domains/domain1`
|===
