== Using Predefined Beans in CDI Applications

Jakarta EE provides predefined beans that implement the following
interfaces.

* `jakarta.transaction.UserTransaction`: A Jakarta Transactions user
transaction.

* `java.security.Principal`: The abstract notion of a principal, which
represents any entity, such as an individual, a corporation, or a login
ID. Whenever the injected principal is accessed, it always represents
the identity of the current caller. For example, a principal is
injected into a field at initialization. Later, a method that uses the
injected principal is called on the object into which the principal was
injected. In this situation, the injected principal represents the
identity of the current caller when the method is run.

* `jakarta.validation.Validator`: A validator for bean instances. The
bean that implements this interface enables a `Validator` object for
the default bean validation object `ValidatorFactory` to be injected.

* `jakarta.validation.ValidatorFactory`: A factory class for returning
initialized `Validator` instances. The bean that implements this
interface enables the default bean validation `ValidatorFactory` object
to be injected.

* `jakarta.servlet.http.HttpServletRequest`: An HTTP request from a
client. The bean that implements this interface enables a servlet to
obtain all the details of a request.

* `jakarta.servlet.http.HttpSession`: An HTTP session between a client
and a server. The bean that implements this interface enables a servlet
to access information about a session and to bind objects to a session.

* `jakarta.servlet.ServletContext`: A context object that servlets can
use to communicate with the servlet container.

To inject a predefined bean, create an injection point to obtain an
instance of the bean by using the `jakarta.annotation.Resource`
annotation for resources or the `jakarta.inject.Inject` annotation for
CDI beans. For the bean type, specify the class name of the interface
the bean implements.

[[injection-of-predefined-beans]]
[width="80%",cols="20%a,20%,40%a",title="Injection of Predefined Beans"]
|===
|Predefined Bean |Resource or CDI Bean |Injection Example

|`UserTransaction` |Resource |`@Resource UserTransaction transaction;`

|`Principal` |Resource |`@Resource Principal principal;`

|`Validator` |Resource |`@Resource Validator validator;`

|`ValidatorFactory` |Resource |`@Resource ValidatorFactory factory;`

|`HttpServletRequest` |CDI bean |`@Inject HttpServletRequest req;`

|`HttpSession` |CDI bean |`@Inject HttpSession session;`

|`ServletContext` |CDI bean |`@Inject ServletContext context;`
|===

Predefined beans are injected with dependent scope and the predefined
default qualifier `@Default`.

For more information about injecting resources, see
<<resource-injection>>.

The following code snippet shows how to use the `@Resource` and
`@Inject` annotations to inject predefined beans. This code snippet
injects a user transaction and a context object into the servlet class
`TransactionServlet`. The user transaction is an instance of the
predefined bean that implements the
`jakarta.transaction.UserTransaction` interface. The context object is
an instance of the predefined bean that implements the
`jakarta.servlet.ServletContext` interface.

[source,java]
----
import jakarta.annotation.Resource;
import jakarta.inject.Inject;
import jakarta.servlet.http.HttpServlet;
import jakarta.transaction.UserTransaction;
...
public class TransactionServlet extends HttpServlet {
    @Resource UserTransaction transaction;
    @Inject ServletContext context;
    ...
}
----
