== Developing a Simple Facelets Application: The guessnumber-faces Example Application

This section describes the general steps involved in developing a Jakarta Faces application.
The following tasks are usually required:

* Developing the managed beans

* Creating the pages using the component tags

* Defining page navigation

* Mapping the `FacesServlet` instance

* Adding managed bean declarations

=== Creating a Facelets Application

The example used in this tutorial is the `guessnumber-faces` application.
The application presents you with a page that asks you to guess a number from 0 to 10, validates your input against a random number, and responds with another page that informs you whether you guessed the number correctly or incorrectly.

The source code for this application is in the `_jakartaee-examples_/tutorial/web/faces/guessnumber-faces/` directory.

==== Developing a Managed Bean

In a typical Jakarta Faces application, each page of the application connects to a managed bean that serves as a backing bean.
The backing bean defines the methods and properties that are associated with the components.
In this example, both pages use the same backing bean.

The following managed bean class, `UserNumberBean.java`, generates a random number from 0 to 10 inclusive:

[source,java]
----
package ee.jakarta.tutorial.guessnumber;

import java.io.Serializable;
import java.util.Random;
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;

@Named
@SessionScoped
public class UserNumberBean implements Serializable {

    private static final long serialVersionUID = 5443351151396868724L;
    Integer randomInt = null;
    Integer userNumber = null;
    String response = null;
    private int maximum = 10;
    private int minimum = 0;

    public UserNumberBean() {
        Random randomGR = new Random();
        randomInt = new Integer(randomGR.nextInt(maximum + 1));
        // Print number to server log
        System.out.println("Duke's number: " + randomInt);
    }

    public void setUserNumber(Integer user_number) {
        userNumber = user_number;
    }

    public Integer getUserNumber() {
        return userNumber;
    }

    public String getResponse() {
        if ((userNumber == null) || (userNumber.compareTo(randomInt) != 0)) {
            return "Sorry, " + userNumber + " is incorrect.";
        } else {
            return "Yay! You got it!";
        }
    }

    public int getMaximum() {
        return (this.maximum);
    }

    public void setMaximum(int maximum) {
        this.maximum = maximum;
    }

    public int getMinimum() {
        return (this.minimum);
    }

    public void setMinimum(int minimum) {
        this.minimum = minimum;
    }
}
----

Note the use of the `@Named` annotation, which makes the managed bean accessible through the EL.
The `@SessionScoped` annotation registers the bean scope as `session` to enable you to make multiple guesses as you run the application.

==== Creating Facelets Views

To create a page or view, you add components to the pages, wire the components to backing bean values and properties, and register converters, validators, or listeners on the components.

For the example application, XHTML web pages serve as the front end.
The page of the example application is a page called `greeting.xhtml`.
A closer look at various sections of this web page provides more information.

The first section of the web page declares the document type of the generated HTML output, which is HTML5:

[source,xml]
----
<!DOCTYPE html>
----

The next section specifies the language of the text embedded in the generated HTML output and then declares the XML namespace for the tag libraries that are used in the web page:

[source,xml]
----
<html lang="en"
      xmlns:h="jakarta.faces.html"
      xmlns:f="jakarta.faces.core">
----

The next section uses various tags to insert components into the web page:

[source,xml]
----
    <h:head>
        <title>Guess Number Facelets Application</title>
        <h:outputStylesheet name="css/default.css"/>
    </h:head>
    <h:body>
        <h:form>
            <h:graphicImage name="images/wave.svg"
                            alt="Duke waving his hand" 
                            width="100" height="100" />
            <h1>
                Hi, my name is Duke. I am thinking of a number from
                #{userNumberBean.minimum} to #{userNumberBean.maximum}.
                Can you guess it?
            </h1>
            <div class="input">
                <h:outputLabel id="userNumberLabel" for="userNumber"
                               value="Enter a number from 0 to 10:" />
                <h:inputText id="userNumber"
                             value="#{userNumberBean.userNumber}">
                    <f:validateLongRange minimum="#{userNumberBean.minimum}"
                                         maximum="#{userNumberBean.maximum}" />
                </h:inputText>
                <h:message id="userNumberMessage" for="userNumber" />
            </div>
            <div class="actions">
                <h:commandButton id="guess" value="Guess"
                                 action="#{userNumberBean.guess}">
                    <f:ajax execute="@form"
                            render="userNumberMessage response" />
                </h:commandButton>
            </div>
            <div class="output">
                <h:outputText id="response" value="#{userNumberBean.response}" />
            </div>
        </h:form>
    </h:body>
----

Note the use of the following tags:

* Facelets HTML tags (those beginning with `h:`) to add components

* The Facelets core tag `f:validateLongRange` to validate the user input

An `h:inputText` tag accepts user input and sets the value of the managed bean property `userNumber` through the EL expression `&#35;{userNumberBean.userNumber}`.
The input value is validated for value range by the Jakarta Faces standard validator tag `f:validateLongRange`.

The image file, `wave.svg`, is added to the page as a resource, as is the style sheet.
For more details about the resources facility, see xref:faces-facelets/faces-facelets.adoc#_web_resources[Web Resources].

An `h:commandButton` tag with the ID `guess` starts validation of the input data when a user clicks the button.
Using `f:ajax`, the tag updates the `h:message` associated with the `h:inputText` so that it can display any validation error messages.
Also the `h:outputText` is being updated which shows the response to your input.

=== Configuring the Application

Configuring a Jakarta Faces application involves mapping the Faces Servlet in the web deployment descriptor file, such as a `web.xml` file, and possibly adding managed bean declarations, navigation rules, and resource bundle declarations to the application configuration resource file, `faces-config.xml`.

If you are using NetBeans IDE, a web deployment descriptor file is automatically created for you.
In such an IDE-created `web.xml` file, change the default greeting page, which is `index.xhtml`, to `greeting.xhtml`.
Here is an example `web.xml` file, showing this change in bold.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd"
         version="6.0">
    <context-param>
        <param-name>jakarta.faces.PROJECT_STAGE</param-name>
        <param-value>Development</param-value>
    </context-param>
    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>jakarta.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>
    <welcome-file-list>
        <welcome-file>greeting.xhtml</welcome-file>
    </welcome-file-list>
</web-app>
----

Note the use of the context parameter `PROJECT_STAGE`.
This parameter identifies the status of a Jakarta Faces application in the software lifecycle.

The stage of an application can affect the behavior of the application.
For example, if the project stage is defined as `Development`, debugging information is automatically generated for the user.
If not defined by the user, the default project stage is `Production`.

=== Running the guessnumber-faces Facelets Example

You can use either NetBeans IDE or Maven to build, package, deploy, and run the `guessnumber-faces` example.

==== To Build, Package, and Deploy the guessnumber-faces Example Using NetBeans IDE

. Make sure that GlassFish Server has been started (see xref:intro:usingexamples/usingexamples.adoc#_starting_and_stopping_glassfish_server[Starting and Stopping GlassFish Server]).

. From the *File* menu, choose *Open Project*.

. In the Open Project dialog box, navigate to:
+
----
jakartaee-examples/tutorial/web/faces
----

. Select the `guessnumber-faces` folder.

. Click *Open Project*.

. In the *Projects* tab, right-click the `guessnumber-faces` project and select *Build*.
+
This option builds the example application and deploys it to your GlassFish Server instance.

==== To Build, Package, and Deploy the guessnumber-faces Example Using Maven

. Make sure that GlassFish Server has been started (see xref:intro:usingexamples/usingexamples.adoc#_starting_and_stopping_glassfish_server[Starting and Stopping GlassFish Server]).

. In a terminal window, go to:
+
----
jakartaee-examples/tutorial/web/faces/guessnumber-faces/
----

. Enter the following command:
+
[source,shell]
----
mvn install
----
+
This command builds and packages the application into a WAR file, `guessnumber-faces.war`, that is located in the `target` directory.
It then deploys it to the server.

==== To Run the guessnumber-faces Example

. Open a web browser.

. Enter the following URL in your web browser:
+
----
http://localhost:8080/guessnumber-faces
----

. In the field, enter a number from 0 to 10 and click Submit.
+
Another page appears, reporting whether your guess is correct or incorrect.

. If you guessed incorrectly, click Back to return to the main page.
+
You can continue to guess until you get the correct answer, or you can look in the server log, where the `UserNumberBean` constructor displays the correct answer.
