[[GIRDR]][[jakarta-ee-8-apis-in-the-java-platform-standard-edition-8]]

== Jakarta EE 8 APIs in the Java Platform, Standard Edition 8

Several APIs that are required by the Jakarta EE 8 platform are included in
the Java Platform, Standard Edition 8 (Java SE 8) and are thus available
to Jakarta EE applications.

[[BNADA]][[java-database-connectivity-api]]

=== Java Database Connectivity API

The Java Database Connectivity (JDBC) API lets you invoke SQL commands
from Java programming language methods. You use the JDBC API in an
enterprise bean when you have a session bean access the database. You
can also use the JDBC API from a servlet or a JSP page to access the
database directly without going through an enterprise bean.

The JDBC API has two parts:

* An application-level interface used by the application components to
access a database
* A service provider interface to attach a JDBC driver to the Jakarta EE
platform

The Jakarta EE 8 platform requires JDBC 4.1.

[[BNADC]][[java-naming-and-directory-interface-api]]

=== Java Naming and Directory Interface API

The Java Naming and Directory Interface (JNDI) API provides naming and
directory functionality, enabling applications to access multiple naming
and directory services, such as LDAP, DNS, and NIS. The JNDI API
provides applications with methods for performing standard directory
operations, such as associating attributes with objects and searching
for objects using their attributes. Using JNDI, a Jakarta EE application
can store and retrieve any type of named Java object, allowing Jakarta EE
applications to coexist with many legacy applications and systems.

Jakarta EE naming services provide application clients, enterprise beans,
and web components with access to a JNDI naming environment. A naming
environment allows a component to be customized without the need to
access or change the component's source code. A container implements the
component's environment and provides it to the component as a JNDI
naming context.

The naming environment provides four logical namespaces: `java:comp`,
`java:module`, `java:app`, and `java:global` for objects available to
components, modules, or applications or shared by all deployed
applications. A Jakarta EE component can access named system-provided and
user-defined objects. The names of some system-provided objects, such as
a default JDBC `DataSource` object, a default JMS connection factory,
and a JTA `UserTransaction` object, are stored in the `java:comp`
namespace. The Jakarta EE platform allows a component to name user-defined
objects, such as enterprise beans, environment entries, JDBC
`DataSource` objects, and messaging destinations.

A Jakarta EE component can also locate its environment naming context by
using JNDI interfaces. A component can create a
`javax.naming.InitialContext` object and look up the environment naming
context in `InitialContext` under the name `java:comp/env`. A
component's naming environment is stored directly in the environment
naming context or in any of its direct or indirect subcontexts.

[[BNACT]][[jakarta-activation]]

=== Jakarta Activation

The Jakarta Activation is used by the Jakarta Mail.
Jakarta Activation provides standard services to determine the type of an arbitrary
piece of data, encapsulate access to it, discover the operations
available on it, and create the appropriate JavaBeans component to
perform those operations.

[[BNACU]][[java-api-for-xml-processing]]

=== Java API for XML Processing

The Java API for XML Processing (JAXP), part of the Java SE platform,
supports the processing of XML documents using Document Object Model
(DOM), Simple API for XML (SAX), and Extensible Stylesheet Language
Transformations (XSLT). JAXP enables applications to parse and transform
XML documents independently of a particular XML-processing
implementation.

JAXP also provides namespace support, which lets you work with schemas
that might otherwise have naming conflicts. Designed to be flexible,
JAXP lets you use any XML-compliant parser or XSL processor from within
your application and supports the Worldwide Web Consortium (W3C) schema.
You can find information on the W3C schema at
`http://www.w3.org/XML/Schema`.

[[BNACW]][[java-architecture-for-xml-binding]]

=== Java Architecture for XML Binding

The Java Architecture for XML Binding (JAXB) provides a convenient way
to bind an XML schema to a representation in Java language programs.
JAXB can be used independently or in combination with Jakarta XML Web Services, in which
case it provides a standard data binding for web service messages. All
Jakarta EE application client containers, web containers, and Jakarta Enterprise Beans
containers support the JAXB API.

The Jakarta EE 8 platform requires JAXB 2.2.

[[BNACV]][[jakarta-xml-web-services]]

=== Jakarta XML Web Services

The Jakarta XML Web Services specification provides
support for web services that use the JAXB API for binding XML data to
Java objects. The Jakarta XML Web Services specification defines client APIs for accessing
web services as well as techniques for implementing web service
endpoints. The Implementing Enterprise Web Services specification
describes the deployment of Jakarta XML Web Services based services and clients. The Jakarta Enterprise Beans
and Jakarta Servlet specifications also describe aspects of such
deployment. Jakarta XML Web Services based applications can be deployed using any of these
deployment models.

The Jakarta XML Web Services specification describes the support for message handlers that
can process message requests and responses. In general, these message
handlers execute in the same container and with the same privileges and
execution context as the Jakarta XML Web Services client or endpoint component with which
they are associated. These message handlers have access to the same JNDI
namespace as their associated component. Custom serializers and
deserializers, if supported, are treated in the same way as message
handlers.

The Jakarta EE 8 platform requires Jakarta XML Web Services 2.2.

[[BNACX]][[jakarta-soap-with-attachments]]

=== Jakarta SOAP with Attachments

The Jakarta SOAP with Attachments is a low-level API on
which Jakarta XML Web Services depends. Jakarta SOAP with Attachments enables the production and consumption of
messages that conform to the SOAP 1.1 and 1.2 specifications and the
Jakarta SOAP with Attachments note. Most developers do not use the Jakarta SOAP with Attachments,
instead using the higher-level Jakarta XML Web Services API.

[[BNADD]][[java-authentication-and-authorization-service]]

=== Java Authentication and Authorization Service

The Java Authentication and Authorization Service (JAAS) provides a way
for a Jakarta EE application to authenticate and authorize a specific user
or group of users to run it.

JAAS is a Java programming language version of the standard Pluggable
Authentication Module (PAM) framework, which extends the Java platform
security architecture to support user-based authorization.

[[sthref12]][[jakarta-annotations]]

=== Jakarta Annotations

Annotations enable a declarative style of programming in the Java
platform.

The Jakarta EE 8 platform requires Jakarta Annotations 1.2.
