== Eclipse GlassFish Server Tools

Eclipse GlassFish Server is a compliant implementation of the Jakarta
EE platform. In addition to supporting all the APIs described in the
previous sections, Eclipse GlassFish Server includes a number of
Jakarta EE tools that are not part of the Jakarta EE platform but are
provided as a convenience to the developer.

This section briefly summarizes the tools that make up Eclipse
GlassFish Server. Instructions for starting and stopping Eclipse
GlassFish Server, starting the Administration Console, and starting and
stopping Apache Derby are in
xref:using-the-tutorial-examples[xrefstyle=full].

Eclipse GlassFish Server contains the tools listed in
<<glassfish-server-tools>>. Basic usage information for many of
the tools appears throughout the tutorial. For detailed information,
see the online help in the GUI tools.

[[glassfish-server-tools]]
[width="85%" cols="20%a,65%", title="Eclipse GlassFish Server Tools"]
|===
|*Tool* |*Description*
a| Administration Console |A web-based GUI Eclipse GlassFish Server
administration utility. Used to stop Eclipse GlassFish Server and to
manage users, resources, and applications.

|`asadmin` |A command-line Eclipse GlassFish Server administration
utility. Used to start and stop Eclipse GlassFish Server and to manage
users, resources, and applications.

|`appclient` |A command-line tool that launches the application client
container and invokes the client application packaged in the
application client JAR file.

|`capture-schema` |A command-line tool to extract schema information
from a database, producing a schema file that Eclipse GlassFish Server
can use for container-managed persistence.

|`package-appclient` |A command-line tool to package the application
client container libraries and JAR files.

|Apache Derby |A copy of Apache Derby database.

|`xjc` |A command-line tool to transform, or bind, a source XML schema
to a set of JAXB content classes in the Java programming language.

|`schemagen` |A command-line tool to create a schema file for each
namespace referenced in your Java classes.

|`wsimport` |A command-line tool to generate Jakarta XML Web Services
portable artifacts for a given WSDL file. After generation, these
artifacts can be packaged in a WAR file with the WSDL and schema
documents, along with the endpoint implementation, and then deployed.

|`wsgen` |A command-line tool to read a web service endpoint class and
generate all the required Jakarta XML Web Services portable artifacts
for web service deployment and invocation.
|===
