== Jakarta EE 8 Platform Highlights

The key goals of the Jakarta EE 8 platform are to modernize the
infrastructure for enterprise Java for the cloud and microservices
environments, emphasize HTML5 and HTTP/2 support, enhance ease of
development through new Contexts and Dependency Injection features, and
further enhance security and reliability of the platform.

The Jakarta EE 8 platform includes the following new features:

* New technologies, including the following:

** <<jakarta-json-binding>>
** <<jakarta-security>>

* New object model improvements for JSON Processing (see
<<jakarta-json-processing>> for details), including support for the
following:

** JSON Pointer
** JSON Patch
** JSON Merge Patch

* New features for RESTful web services (see
<<jakarta-restful-web-services>> for details)

* New features for servlets (see <<jakarta-servlet-technology>> for
details)

* New features for Jakarta Server Faces components (see
<<jakarta-faces-technology>> for details)

* New Contexts and Dependency Injection features (see
<<jakarta-contexts-and-dependency-injection>> for details)

* New Jakarta Bean Validation features (see <<jakarta-bean-validation>>
for details)
