== Configuring a CDI Application

When your beans are annotated with a scope type, the server recognizes the application as a bean archive and no additional configuration is required.
The possible scope types for CDI beans are listed in <<_using_scopes>>.

CDI uses an optional deployment descriptor named `beans.xml`.
Like other Jakarta EE deployment descriptors, the configuration settings in `beans.xml` are used in addition to annotation settings in CDI classes.
The settings in `beans.xml` override the annotation settings if there is a conflict.
An archive must contain the `beans.xml` deployment descriptor only in certain limited situations, described in xref:cdi-adv/cdi-adv.adoc#_jakarta_contexts_and_dependency_injection_advanced_topics[Jakarta Contexts and Dependency Injection: Advanced Topics].

For a web application, the `beans.xml` deployment descriptor, if present, must be in the `WEB-INF` directory.
For EJB modules or JAR files, the `beans.xml` deployment descriptor, if present, must be in the `META-INF` directory.
