== What is Jakarta EE?

Jakarta EE is a collection of services that help you write enterprise applications that run on the Java Platform.
It provides the infrastructure often required for these applications
so you that you can focus on core features and business logic.

*Enterprise applications* support the high levels of security,
scalability, and reliability that large organizations typically require.
They can be web services, web applications, batch processes, and so on.

The *Java Platform* consists of the Java Virtual Machine, compiler,
standard APIs, and several tools that help you build, deploy, and debug Java applications.
Java is the primary programming language, although the Java Platform supports several others, including Kotlin and Scala.
Most Jakarta EE applications, however, are written in Java. The *Java Platform* is also called *Java Standard Edition (SE)*.

With Jakarta EE, you can pick and choose which services you need,
and you use them with or without other frameworks and libraries.
One framework commonly used with Jakarta EE is https://microprofile.io[MicroProfile^],
which provides additional features commonly used in microservices.

A key benefit of Jakarta EE is that it's a set of open source standards supported by multiple vendors.
Each vendor has their own implementation of the standards,
and the vendors work together to update the standards over time.
This means that you aren't locked into a particular vendor,
and each standard is well-thought-out and based on existing patterns and practices.

Jakarta EE is stable and mature, and used in tens of thousands of mission-critical enterprises applications worldwide;
yet it has evolved over time to keep up with modern computing trends, such as cloud computing.
