== Modifying the Jakarta EE Application

GlassFish Server supports iterative development. Whenever you make a
change to a Jakarta EE application, you must redeploy the application.

=== To Modify a Class File

To modify a class file in an enterprise bean, you change the source
code, recompile it, and redeploy the application. For example, to
update the exchange rate in the `dollarToYen` business method of the
`ConverterBean` class, you would follow these steps.

To modify `ConverterServlet`, the procedure is the same.

. Edit `ConverterBean.java` and save the file.
. Recompile the source file.
.. To recompile `ConverterBean.java` in NetBeans IDE, right-click the
`converter` project and select Run.
+
This recompiles the `ConverterBean.java` file, replaces the old class
file in the build directory, and redeploys the application to GlassFish
Server.
.. Recompile `ConverterBean.java` using Maven.
...  In a terminal window, go to the
tut-install`/examples/ejb/converter/` directory.
...  Enter the following command:
+
[source,shell]
----
mvn install
----
+
This command repackages and deploys the application.
