type=page
status=published
title=Building Web Services with Jakarta XML Web Services
next=jaxws001.html
prev=webservices-intro003.html
~~~~~~
Building Web Services with Jakarta XML Web Services
===================================================

[[BNAYL]][[building-web-services-with-jax-ws]]

31 Building Web Services with Jakarta XML Web Services
------------------------------------------------------


This chapter describes Jakarta XML Web Services, a
technology for building web services and clients that communicate using
XML. Jakarta XML Web Services allows developers to write message-oriented as well as
Remote Procedure Call–oriented (RPC-oriented) web services.

The following topics are addressed here:

* link:jaxws001.html#A1250966[Overview of Jakarta XML Web Services]
* link:jaxws002.html#BNAYN[Creating a Simple Web Service and Clients with
Jakarta XML Web Services]
* link:jaxws003.html#BNAZC[Types Supported by Jakarta XML Web Services]
* link:jaxws004.html#BNAZD[Web Services Interoperability and Jakarta XML Web Services]
* link:jaxws005.html#BNAZE[Further Information about Jakarta XML Web Services]
