type=page
status=published
title=Using Ajax with Jakarta Faces Technology
next=jsf-ajax001.html
prev=jsf-develop003.html
~~~~~~
Using Ajax with Jakarta Faces Technology
===========================================

[[GKIOW]][[using-ajax-with-javaserver-faces-technology]]

13 Using Ajax with Jakarta Faces Technology
----------------------------------------------


This chapter describes using Ajax functionality in Jakarta Faces web
applications. Ajax is an acronym for Asynchronous JavaScript and XML, a
group of web technologies that enable creation of dynamic and highly
responsive web applications. Using Ajax, web applications can retrieve
content from the server without interfering with the display on the
client. In the Jakarta EE platform, Jakarta Faces technology provides
built-in support for Ajax.

The following topics are addressed here:

* link:jsf-ajax001.html#GKIGR[Overview of Ajax]
* link:jsf-ajax002.html#GKINL[Using Ajax Functionality with Jakarta Server
Faces Technology]
* link:jsf-ajax003.html#GKABR[Using Ajax with Facelets]
* link:jsf-ajax004.html#GKACE[Sending an Ajax Request]
* link:jsf-ajax005.html#GKDDF[Monitoring Events on the Client]
* link:jsf-ajax006.html#GKDCB[Handling Errors]
* link:jsf-ajax007.html#GKDBR[Receiving an Ajax Response]
* link:jsf-ajax008.html#GKUAR[Ajax Request Lifecycle]
* link:jsf-ajax009.html#GKHYH[Grouping of Components]
* link:jsf-ajax010.html#GKAAM[Loading JavaScript as a Resource]
* link:jsf-ajax011.html#GKOKB[The ajaxguessnumber Example Application]
* link:jsf-ajax012.html#GKSDK[Further Information about Ajax in
Jakarta Faces Technology]


