== Jakarta Messaging Overview

This overview defines the concept of messaging, describes Jakarta Messaging and where it can be used, and explains how Jakarta Messaging works within the Jakarta EE platform.

=== What Is Messaging?

Messaging is a method of communication between software components or applications.
A messaging system is a peer-to-peer facility: A messaging client can send messages to, and receive messages from, any other client.
Each client connects to a messaging agent that provides facilities for creating, sending, receiving, and reading messages.

Messaging enables distributed communication that is loosely coupled.
A component sends a message to a destination, and the recipient can retrieve the message from the destination.
What makes the communication loosely coupled is that the destination is all that the sender and receiver have in common.
The sender and the receiver do not have to be available at the same time in order to communicate.
In fact, the sender does not need to know anything about the receiver; nor does the receiver need to know anything about the sender.
The sender and the receiver need to know only which message format and which destination to use.
In this respect, messaging differs from tightly coupled technologies, such as Remote Method Invocation (RMI), which require an application to know a remote application's methods.

Messaging also differs from electronic mail (email), which is a method of communication between people or between software applications and people.
Messaging is used for communication between software applications or software components.

=== What Is Jakarta Messaging?

Jakarta Messaging is a Java API that allows applications to create, send, receive, and read messages.
Jakarta Messaging defines a common set of interfaces and associated semantics that allow programs written in the Java programming language to communicate with other messaging implementations.

Jakarta Messaging minimizes the set of concepts a programmer must learn in order to use messaging products but provides enough features to support sophisticated messaging applications.
It also strives to maximize the portability of Messaging applications across providers.

Jakarta Messaging enables communication that is not only loosely coupled but also

* Asynchronous: A receiving client does not have to receive messages at the same time the sending client sends them.
The sending client can send them and go on to other tasks; the receiving client can receive them much later.

* Reliable: A messaging provider that implements Jakarta Messaging can ensure that a message is delivered once and only once.
Lower levels of reliability are available for applications that can afford to miss messages or to receive duplicate messages.

The current version of the Jakarta Messaging specification is Version 3.0.

=== When Can You Use Jakarta Messaging?

An enterprise application provider is likely to choose a messaging API over a tightly coupled API, such as a remote procedure call (RPC), under the following circumstances.

* The provider wants the components not to depend on information about other components' interfaces, so components can be easily replaced.

* The provider wants the application to run whether or not all components are up and running simultaneously.

* The application business model allows a component to send information to another and to continue to operate without receiving an immediate response.

For example, components of an enterprise application for an automobile manufacturer can use Jakarta Messaging in situations like the following.

* The inventory component can send a message to the factory component when the inventory level for a product goes below a certain level so the factory can make more cars.

* The factory component can send a message to the parts components so the factory can assemble the parts it needs.

* The parts components in turn can send messages to their own inventory and order components to update their inventories and to order new parts from suppliers.

* Both the factory and the parts components can send messages to the accounting component to update budget numbers.

* The business can publish updated catalog items to its sales force.

Using messaging for these tasks allows the various components to interact with one another efficiently, without tying up network or other resources.
<<messaging-in-an-enterpise-application>> illustrates how this simple example might work.

[[messaging-in-an-enterpise-application]]
.Messaging in an Enterprise Application
image::jakartaeett_dt_026.svg["Diagram showing messaging between various departments in an enterprise"]

Manufacturing is only one example of how an enterprise can use the Jakarta Messaging API.
Retail applications, financial services applications, health services applications, and many others can make use of messaging.

=== How Does Jakarta Messaging Work with the Jakarta EE Platform?

When JMS was first introduced, its most important purpose was to allow Java applications to access existing messaging-oriented middleware (MOM) systems.
Since that time, many vendors have adopted and implemented JMS, so a Jakarta Messaging product can now provide a complete messaging capability for an enterprise.

Jakarta Messaging is an integral part of the Jakarta EE platform, and application developers can use messaging with Jakarta EE components. Jakarta Messaging 2.0 is part of the Jakarta EE 8 release.

Jakarta Messaging in the Jakarta EE platform has the following features.

* Application clients, Jakarta Enterprise Beans components, and web components can send or synchronously receive a Jakarta Messaging message.
Application clients can in addition set a message listener that allows Jakarta Messaging messages to be delivered to it asynchronously by being notified when a message is available.

* Message-driven beans, which are a kind of enterprise bean, enable the asynchronous consumption of messages in the enterprise bean container.
An application server typically pools message-driven beans to implement concurrent processing of messages.

* Message send and receive operations can participate in Jakarta transactions, which allow Jakarta Messaging operations and database accesses to take place within a single transaction.

Jakarta Messaging enhances the other parts of the Jakarta EE platform by simplifying enterprise development, allowing loosely coupled, reliable, asynchronous interactions among Jakarta EE components and legacy systems capable of messaging.
A developer can easily add new behavior to a Jakarta EE application that has existing business events by adding a new message-driven bean to operate on specific business events.
The Jakarta EE platform, moreover, enhances Jakarta Messaging by providing support for Jakarta Transactions and allowing for the concurrent consumption of messages.
For more information, see the Jakarta Enterprise Beans specification, v4.0.

The Jakarta Messaging provider can be integrated with the application server using the Jakarta Connectors.
You access the Messaging provider through a resource adapter.
This capability allows vendors to create Messaging providers that can be plugged in to multiple application servers, and it allows application servers to support multiple Messaging providers.
For more information, see the Jakarta Connectors specification, v2.0.
