== Updating Multiple Databases

The Jakarta EE transaction manager controls all enterprise bean transactions except for bean-managed JDBC transactions.
The Jakarta EE transaction manager allows an enterprise bean to update multiple databases within a transaction.
<<_updating_multiple_databases_2>> and <<_updating_multiple_databases_across_jakarta_ee_servers>> show two scenarios for updating multiple databases in a single transaction.

In <<_updating_multiple_databases_2>>, the client invokes a business method in `Bean-A`.
The business method begins a transaction, updates Database X, updates Database Y, and invokes a business method in `Bean-B`.
The second business method updates Database Z and returns control to the business method in `Bean-A`, which commits the transaction.
All three database updates occur in the same transaction.

In <<_updating_multiple_databases_across_jakarta_ee_servers>>, the client calls a business method in `Bean-A`, which begins a transaction and updates Database X.
Then `Bean-A` invokes a method in `Bean-B`, which resides in a remote Jakarta EE server.
The method in `Bean-B` updates Database Y.
The transaction managers of the Jakarta EE servers ensure that both databases are updated in the same transaction.

[[_updating_multiple_databases_2]]
.Updating Multiple Databases
image::common:jakartaeett_dt_051.svg["A diagram showing Bean-A updating databases X and Y, and Bean-B updating database Z."]

[[_updating_multiple_databases_across_jakarta_ee_servers]]
.Updating Multiple Databases Across Jakarta EE Servers
image::common:jakartaeett_dt_052.svg["A diagram showing Bean-A on one Jakarta EE server updating database X, and Bean-B on another Jakarta EE server updating database Y."]
