== Securing Enterprise Information Systems Applications

In Enterprise Information Systems (EIS) applications, components request a connection to an EIS resource.

=== Overview of Securing Enterprise Information Systems Applications

As part of this connection, the EIS can require a sign-on for the requester to access the resource.
The application component provider has two choices for the design of the EIS sign-on.

* Container-managed sign-on: The application component lets the container take the responsibility of configuring and managing the EIS sign-on.
The container determines the user name and password for establishing a connection to an EIS instance.

* Component-managed sign-on: The application component code manages EIS sign-on by including code that performs the sign-on process to an EIS.

You can also configure security for resource adapters.
See <<configuring-resource-adapter-security>>.

=== Container-Managed Sign-On

In container-managed sign-on, an application component does not have to pass any sign-on security information to the `getConnection()` method.
The security information is supplied by the container, as shown in the following example (the method call is highlighted in bold):

[source,java]
----
// Business method in an application component
Context initctx = new InitialContext();
// Perform JNDI lookup to obtain a connection factory
jakarta.resource.cci.ConnectionFactory cxf =
    (jakarta.resource.cci.ConnectionFactory)initctx.lookup(
    "java:comp/env/eis/MainframeCxFactory");
// Invoke factory to obtain a connection. The security
// information is not passed in the getConnection method
jakarta.resource.cci.Connection cx = cxf.getConnection();
...
----

=== Component-Managed Sign-On

In component-managed sign-on, an application component is responsible for passing the needed sign-on security information for the resource to the `getConnection` method.
For example, security information might be a user name and password, as shown here (the method call is highlighted in bold):

[source,java]
----
// Method in an application component
Context initctx = new InitialContext();

// Perform JNDI lookup to obtain a connection factory
jakarta.resource.cci.ConnectionFactory cxf =
    (jakarta.resource.cci.ConnectionFactory)initctx.lookup(
    "java:comp/env/eis/MainframeCxFactory");

// Get a new ConnectionSpec
com.myeis.ConnectionSpecImpl properties = //..

// Invoke factory to obtain a connection
properties.setUserName("...");
properties.setPassword("...");
jakarta.resource.cci.Connection cx =
    cxf.getConnection(properties);
...
----

=== Configuring Resource Adapter Security

A resource adapter is a system-level software component that typically implements network connectivity to an external resource manager.
A resource adapter can extend the functionality of the Jakarta EE platform either by implementing one of the Jakarta EE standard service APIs, such as a JDBC driver, or by defining and implementing a resource adapter for a connector to an external application system.
Resource adapters can also provide services that are entirely local, perhaps interacting with native resources.
Resource adapters interface with the Jakarta EE platform through the Jakarta EE service provider interfaces (Jakarta EE SPI).
A resource adapter that uses the Jakarta EE SPIs to attach to the Jakarta EE platform will be able to work with all Jakarta EE products.

To configure the security settings for a resource adapter, you need to edit the resource adapter descriptor file, `ra.xml`.
Here is an example of the part of an `ra.xml` file that configures security properties for a resource adapter:

[source,xml]
----
<authentication-mechanism>
    <authentication-mechanism-type>
        BasicPassword
    </authentication-mechanism-type>
    <credential-interface>
        jakarta.resource.spi.security.PasswordCredential
    </credential-interface>
</authentication-mechanism>
<reauthentication-support>false</reauthentication-support>
----

You can find out more about the options for configuring resource adapter security by reviewing `_as-install_/lib/schemas/connector_2_0.xsd`.
You can configure the following elements in the resource adapter deployment descriptor file.

* Authentication mechanisms: Use the `authentication-mechanism` element to specify an authentication mechanism supported by the resource adapter.
This support is for the resource adapter, not for the underlying EIS instance.
+
There are two supported mechanism types:

** `BasicPassword`, which supports the following interface:
+
----
jakarta.resource.spi.security.PasswordCredential
----

** `Kerbv5`, which supports the following interface:
+
----
jakarta.resource.spi.security.GenericCredential
----
+
GlassFish Server does not currently support this mechanism type.

* Reauthentication support: Use the `reauthentication-support` element to specify whether the resource adapter implementation supports reauthentication of existing `Managed-Connection` instances.
Options are `true` or `false`.

* Security permissions: Use the `security-permission` element to specify a security permission that is required by the resource adapter code.
Support for security permissions is optional and is not supported in the current release of GlassFish Server.
You can, however, manually update the `server.policy` file to add the relevant permissions for the resource adapter.
+
The security permissions listed in the deployment descriptor are different from those required by the default permission set as specified in the connector specification.
+
For more information on the implementation of the security permission specification, see the security policy file documentation listed in <<further-information-about-advanced-security-topics>>.

In addition to specifying resource adapter security in the `ra.xml` file, you can create a security map for a connector connection pool to map an application principal or a user group to a back-end EIS principal.
The security map is usually used if one or more EIS back-end principals are used to execute operations (on the EIS) initiated by various principals or user groups in the application.

=== Mapping an Application Principal to EIS Principals

When using GlassFish Server, you can use security maps to map the caller identity of the application (principal or user group) to a suitable EIS principal in container-managed transaction-based scenarios.
When an application principal initiates a request to an EIS, GlassFish Server first checks for an exact principal by using the security map defined for the connector connection pool to determine the mapped back-end EIS principal.
If there is no exact match, GlassFish Server uses the wildcard character specification, if any, to determine the mapped back-end EIS principal.
Security maps are used when an application user needs to execute an EIS operation that requires execution as a specific identity in the EIS.

To work with security maps, use the Administration Console.
From the Administration Console, follow these steps to get to the security maps page.

. In the navigation tree, expand the Resources node.

. Expand the Connectors node.

. Select the Connector Connection Pools node.

. On the Connector Connection Pools page, click the name of the connection pool for which you want to create a security map.

. Click the Security Maps tab.

. Click New to create a new security map for the connection pool.

. Enter a name by which you will refer to the security map, as well as the other required information.
+
Click Help for more information on the individual options.
