== Annotated Endpoints

The following example shows how to create the same endpoint from
<<programmatic-endpoints>> using annotations instead:

[source,java]
----
@ServerEndpoint("/echo")
public class EchoEndpoint {
   @OnMessage
   public void onMessage(Session session, String msg) {
      try {
         session.getBasicRemote().sendText(msg);
      } catch (IOException e) { ... }
   }
}
----

The annotated endpoint is simpler than the equivalent programmatic
endpoint, and it is deployed automatically with the application to the
relative path defined in the `ServerEndpoint` annotation. Instead of
having to create an additional class for the message handler, this
example uses the `OnMessage` annotation to designate the method invoked
to handle messages.

<<websocket-endpoint-lifecycle-annotations>> lists the annotations
available in the `jakarta.websocket` package to designate the methods
that handle lifecycle events. The examples in the table show the most
common parameters for these methods. See the API reference for details
on what combinations of parameters are allowed in each case.

[[websocket-endpoint-lifecycle-annotations]]
[width="80%",cols="20%a,20%,60%a",title="WebSocket Endpoint Lifecycle Annotations"]
|===
|Annotation |Event |Example

|`OnOpen` |Connection opened |
[source,java]
----
@OnOpen
public void open(Session session,
                 EndpointConfig conf) { }
----
{empty}

|`OnMessage` |Message received a|
[source,java]
----
@OnMessage
public void message(Session session,
                    String msg) { }
----
{empty}

|`OnError` |Connection error a|
[source,java]
----
@OnError
public void error(Session session,
                  Throwable error) { }
----
{empty}

|`OnClose` |Connection closed a|
[source,java]
----
@OnClose
public void close(Session session,
                  CloseReason reason) { }
----
{empty}

|===
