== Hello World Web Application Using Jakarta Servlet

The `helloServlet` application is a web application that uses Jakarta Servlet take a name as an HTTP request parameter, generate the greeting and return it as an HTTP response.
As a service-oriented web application, the response is represented as plain text.

The source code for this application is in the `_tut-install_/examples/web/servlet/helloServlet/` directory.

=== The Servlet

In a typical Jakarta Servlet application, the class must extend `jakarta.servlet.http.HttpServlet` and override one of the `doXxx()` methods where `Xxx` represents the HTTP method of interest.
Such a class is in the Jakarta Servlet world called a _Servlet_.

For this Hello World web application, the `src/main/java/jakartaee/tutorial/servlet/Greeting.java` servlet listens on HTTP GET requests and extracts the `name` request parameter as input and creates the `greeting` as output.

[source,java]
----
package jakartaee.tutorial.servlet;

import java.io.IOException;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/greeting")
public class Greeting extends HttpServlet {

    @Override
    public void doGet
        (HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException
    {
        var name = request.getParameter("name");

        if (name == null || name.isBlank()) {
            response.sendError(HttpServletResponse.SC_BAD_REQUEST);
            return;
        }

        var greeting = "Hello, " + name + "!";

        response.setContentType("text/plain");
        response.getWriter().write(greeting);
    }
}
----

=== Mapping URLs to Web Components

When the servlet container receives a request, it must determine which web component should handle the request.
The servlet container does so by mapping the URL contained in the request to a web component.
A URL contains the context path and, optionally, a URL pattern:

----
http(s)://host:port/context-path[/url-pattern]
----

You can set the URL pattern for a servlet by using the `@WebServlet` annotation in the servlet source file or by using `<servlet-mapping>` entry in the Jakarta Servlet deployment descriptor file, the `src/main/webapp/WEB-INF/web.xml`.
In the `Greeting` servlet example the `@WebServlet` annotation indicates that the URL pattern is `/greeting`.
Therefore, when the servlet is deployed to a local server listening on `http://localhost:8080` with the context path set to `helloServlet`, it is accessed with the following URL:

----
http://localhost:8080/helloServlet/greeting
----

The Hello World example will return a HTTP 400 error as response indicating a 'Bad Request'.
When specifying the name as a request parameter in the following URL:

----
http://localhost:8080/helloServlet/greeting?name=Duke
----

Then it will return the response `Hello, Duke!`.

















=== Running the hello2 Example

You can use either NetBeans IDE or Maven to build, package, deploy, and run the `hello2` example.

==== To Build, Package, Deploy and Run the hello2 Example Using NetBeans IDE

To build, package, deploy and run the `hello2` example using NetBeans IDE:

. Start GlassFish Server as described in <<to-start-glassfish-server-using-netbeans-ide>>, if you have not already done so.

. From the *File* menu, choose *Open Project*.

. In the Open Project dialog box, navigate to:
+
----
tut-install/examples/web/servlet
----

. Select the `hello2` folder.

. Click *Open Project*.

. In the *Projects* tab, right-click the `hello2` project and select *Build* to package and deploy the project.

. In a web browser, open the following URL:
+
----
http://localhost:8080/hello2/greeting
----
+
The URL specifies the context root, followed by the URL pattern.
+
The application looks much like the `hello1` application.
The major difference is that after you click Submit the response appears below the greeting, not on a separate page.

====  To Build, Package, Deploy and Run the hello2 Example Using Maven

To build, package, deploy and run the `hello2` example using Maven:

. Start GlassFish Server as described in <<to-start-glassfish-server-using-the-command-line>>, if you have not already done so.

. In a terminal window, go to:
+
----
tut-install/examples/web/servlet/hello2/
----

. Enter the following command:
+
[source,shell]
----
mvn install
----
+
This target builds the WAR file, copies it to the `_tut-install_/examples/web/hello2/target/` directory, and deploys it.

. In a web browser, open the following URL:
+
----
http://localhost:8080/hello2/greeting
----
+
The URL specifies the context root, followed by the URL pattern.
+
The application looks much like the `hello1` application.
The major difference is that after you click Submit the response appears below the greeting, not on a separate page.
