== Hello World Web Application Using Jakarta Faces

The `helloFaces` application is a web application that uses Jakarta Faces take a name as an HTTP request parameter, generate the greeting and return it as an HTTP response.
The response is represented as a HTML document.
There is an image file as asset.

The source code for this application is in the `_tut-install_/examples/web/faces/helloFaces/` directory.

Jakarta Faces is a component based MVC framework that provides its own servlet as controller (the "C" part of MVC).
The model and the view are usually provided by you, the web developer.

=== The Model

In a typical Jakarta Faces application, the model is represented by a JavaBean class.
Such a JavaBean class is in the Jakarta Faces world called a _Backing Bean_.

For this Hello World web application, the backing bean defines a `name` property along with a getter and setter, a `greeting` property along with a getter, and a `submit` action method which creates the `greeting` as output based on `name` as input.

[source,java]
----
package jakartaee.tutorial.faces;

import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Named;

@Named
@RequestScoped
public class Hello {

    private String name;
    private String greeting;

    public void submit() {
        greeting = "Hello, " + name + "!";
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String getGreeting() {
        return greeting;
    }
}
----

Note that a getter is required for output and that a setter is only required for input.

We'll briefly go through the annotations that are used here:

* `@Named` -- gives the bean a name, which is primarily used to reference it in Expression Language (EL).
  Without any attributes this defaults to the simple class name with the first letter in lowercase.
  This backing bean will thus be available as `#{hello}` in EL.
* `@RequestScoped` -- gives the bean a scope, which is essentially its lifespan.
  In this case that lifespan is the duration of an HTTP request.
  When the HTTP request ends, then the bean instance is destroyed.

=== The View

In a typical Jakarta Faces application, the view is represented by a XHTML file.
Such a XHTML file is in the Jakarta Faces world called a _Facelets File_ or just _Facelet_.
In Jakarta Faces, the view technology is pluggable and Facelets is used as the default view technology.
XHTML markup is being used because it allows the framework to easily use a XML parser to find components of interest and to generate HTML output.

For this Hello World web application, the Facelet defines a header with an image and a heading, and a form with a label, input field, messages holder and a command button:

[source,xml]
----
<!DOCTYPE html>
<html lang="en" xmlns:h="jakarta.faces.html">
    <h:head>
        <title>Jakarta Faces Hello World</title>
    </h:head>
    <h:body>
        <header>
            <h:graphicImage name="duke.svg" alt="Duke waving his hand" />
            <h1>Hello, my name is Duke. What's yours?</h1>
        </header>
        <h:form>
            <div>
                <h:outputLabel for="username"
                               value="My name is:" />
                <h:inputText id="username"
                             value="#{hello.name}"
                             required="true"
                             requiredMessage="Error: A name is required."
                             maxlength="25" />
                <h:messages for="username" />
            </div>
            <div>
                <h:commandButton value="Submit"
                                 action="#{hello.submit}" />
            </div>
        </h:form>
        <h2>#{hello.greeting}</h2>
    </h:body>
</html>
----

We'll briefly go through the Jakarta Faces-specific XHTML tags that are used here:

* `<h:head>` -- generates the HTML `<head>`.
  It gives Jakarta Faces the opportunity to automatically include any necessary JS and CSS files in the generated HTML head.
* `<h:body>` -- generates the HTML `<body>`.
  It gives Jakarta Faces the opportunity to automatically include any necessary JS files in the end of the generated HTML body.
* `<h:form>` -- generates the HTML `<form>`.
  It gives Jakarta Faces the opportunity to automatically include a hidden field representing the view state.
* `<h:outputLabel>` -- generates the HTML `<label>`.
  It gives Jakarta Faces the opportunity to automatically include the label in any conversion or validation messages.
* `<h:inputText>` -- generates the HTML `<input>`.
  It gives Jakarta Faces the opportunity to automatically get and set the value as a backing bean property, as well as to perform any conversion and validation on it.
* `<h:messages>` -- generates the HTML `<ul>` containing any conversion or validation messages.
  It gives Jakarta Faces the opportunity to automatically get and set the value as a backing bean property specified in the `value` attribute, as well as to perform any conversion and validation on it.
* `<h:commandButton>` -- generates the HTML `<input type="submit">`.
  It gives Jakarta Faces the opportunity to automatically invoke the backing bean method specified in the `action` attribute.












+
The most complex element on the page is the `inputText` field.
The `maxlength` attribute specifies the maximum length of the field.
The `required` attribute specifies that the field must be filled out; the `requiredMessage` attribute provides the error message to be displayed if the field is left empty.
The `title` attribute provides the text to be used by screen readers for the visually disabled.
Finally, the `value` attribute contains an expression that will be provided by the `Hello` managed bean.
+
The web page connects to the `Hello` managed bean through the Expression Language (EL) value expression `#{hello.name}`, which retrieves the value of the `name` property from the managed bean.
Note the use of `hello` to reference the managed bean `Hello`.
If no name is specified in the `@Named` annotation of the managed bean, the managed bean is always accessed with the first letter of the class name in lowercase.
+
The Submit `commandButton` element specifies the action as `response`, meaning that when the button is clicked, the `response.xhtml` page is displayed.

. Double-click the `response.xhtml` file to view it.
+
The response page appears.Even simpler than the greeting page, the response page contains a graphic image, a header that displays the expression provided by the managed bean, and a single button whose `action` element transfers you back to the `index.xhtml` page:
+
[source,xml]
----
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="jakarta.faces.html">
    <h:head>
        <title>Facelets Hello Response</title>
    </h:head>
    <h:body>
        <h:form>
            <h:graphicImage url="#{resource['images:duke.waving.gif']}"
                            alt="Duke waving his hand"/>
            <h2>Hello, #{hello.name}!</h2>
            <p></p>
            <h:commandButton id="back" value="Back" action="index" />
        </h:form>
    </h:body>
</html>
----


. Under the Web Pages node, expand the WEB-INF node and double-click the `web.xml` file to view it.
+
The `web.xml` file contains several elements that are required for a Facelets application.
All of the following are created automatically when you use NetBeans IDE to create an application.

* A context parameter specifying the project stage:
+
[source,xml]
----
<context-param>
    <param-name>jakarta.faces.PROJECT_STAGE</param-name>
    <param-value>Development</param-value>
</context-param>
----
+
A context parameter provides configuration information needed by a web application.
An application can define its own context parameters.
In addition, Jakarta Faces technology and Jakarta Servlet technology define context parameters that an application can use.

* A `servlet` element and its `servlet-mapping` element specifying the `FacesServlet`. All files with the `.xhtml` suffix will be matched:
+
[source,xml]
----
<servlet>
    <servlet-name>Faces Servlet</servlet-name>
    <servlet-class>jakarta.faces.webapp.FacesServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
</servlet>
<servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.xhtml</url-pattern>
</servlet-mapping>
----

* A `welcome-file-list` element specifying the location of the landing page:
+
[source,xml]
----
<welcome-file-list>
    <welcome-file>index.xhtml</welcome-file>
</welcome-file-list>
----

==== Introduction to Scopes

In the `Hello.java` class, the annotations `jakarta.inject.Named` and `jakarta.enterprise.context.RequestScoped` identify the class as a managed bean using request scope.
Scope defines how application data persists and is shared.

The most commonly used scopes in Jakarta Faces applications are the following:

Request (`@RequestScoped`):: Request scope persists during a single HTTP request in a web application.
In an application like `hello1`, in which the application consists of a single request and response, the bean uses request scope.

Session (`@SessionScoped`):: Session scope persists across multiple HTTP requests in a web application.
When an application consists of multiple requests and responses where data needs to be maintained, beans use session scope.

Application (`@ApplicationScoped`):: Application scope persists across all users' interactions with a web application.

For more information on scopes in Jakarta Faces technology, see <<using-managed-bean-scopes>>.

=== Packaging and Deploying the hello1 Web Module

A web module must be packaged into a WAR in certain deployment scenarios and whenever you want to distribute the web module.
You can package a web module into a WAR file by using Maven or by using the IDE tool of your choice.
This tutorial shows you how to use NetBeans IDE or Maven to build, package, and deploy the `hello1` sample application.

You can deploy a WAR file to GlassFish Server by:

* Using NetBeans IDE

* Using the `asadmin` command

* Using the Administration Console

* Copying the WAR file into the `_domain-dir_/autodeploy/` directory

Throughout the tutorial, you will use NetBeans IDE or Maven for packaging and deploying.

==== To Build, Package and Deploy the hello1 Web Module Using NetBeans IDE

To build and package the `hello1` web module using NetBeans IDE:

. Start GlassFish Server as described in <<to-start-glassfish-server-using-netbeans-ide>>, if you have not already done so.

. From the *File* menu, choose *Open Project*.

. In the Open Project dialog box, navigate to:
+
----
tut-install/examples/web/faces
----

. Select the `hello1` folder.

. Click *Open Project*.

. In the *Projects* tab, right-click the `hello1` project and select *Build*. This command deploys the project to the server.

==== To Build, Package and Deploy the hello1 Web Module Using Maven

To build and package the `hello1` web module using Maven:

. Start GlassFish Server as described in <<to-start-glassfish-server-using-the-command-line>>, if you have not already done so.

. In a terminal window, go to:
+
----
tut-install/examples/web/faces/hello1/
----

. Enter the following command:
+
[source,shell]
----
mvn install
----
+
This command spawns any necessary compilations and creates the WAR file in `_tut-install_/examples/web/faces/hello1/target/`.
It then deploys the project to the server.

=== Viewing Deployed Web Modules

GlassFish Server provides two ways to view the deployed web modules: the Administration Console and the `asadmin` command.
You can also use NetBeans IDE to view deployed modules.

==== To View Deployed Web Modules Using the Administration Console

To view deployed web modules using the Administration Console:

. Open the URL http://localhost:4848/[^] in a browser.

. Select the Applications node.
+
The deployed web modules appear in the Deployed Applications table.

==== To View Deployed Web Modules Using the asadmin Command

Enter the following command:

[source,shell]
----
asadmin list-applications
----

==== To View Deployed Web Modules Using NetBeans IDE

To view deployed web modules using NetBeans IDE:

. In the *Services* tab, expand the *Servers* node, then expand the *GlassFish Server* node.

. Expand the *Applications* node to view the deployed modules.

=== Running the Deployed hello1 Web Module

Now that the web module is deployed, you can view it by opening the application in a web browser.
By default, the application is deployed to host `localhost` on port 8080.
The context root of the web application is `hello1`.

To run the deployed `hello1` web module:

. Open a web browser.

. Enter the following URL:
+
----
http://localhost:8080/hello1/
----

. In the field, enter your name and click Submit.
+
The response page displays the name you submitted. Click Back to try again.

==== Dynamic Reloading of Deployed Modules

If dynamic reloading is enabled, you do not have to redeploy an application or module when you change its code or deployment descriptors.
All you have to do is copy the changed pages or class files into the deployment directory for the application or module.
The deployment directory for a web module named context-root is `_domain-dir_/applications/_context-root_`.
The server checks for changes periodically and redeploys the application, automatically and dynamically, with the changes.

This capability is useful in a development environment because it allows code changes to be tested quickly.
Dynamic reloading is not recommended for a production environment, however, because it may degrade performance.
In addition, whenever a reload takes place, the sessions at that time become invalid, and the client must restart the session.

In GlassFish Server, dynamic reloading is enabled by default.

=== Undeploying the hello1 Web Module

You can undeploy web modules and other types of enterprise applications by using either NetBeans IDE or Maven.

==== To Undeploy the hello1 Web Module Using NetBeans IDE

To undeploy the `hello1` web module using NetBeans IDE:

. In the *Services* tab, expand the *Servers* node, then expand the *GlassFish Server* node.

. Expand the *Applications* node.

. Right-click the `hello1` module and select *Undeploy*.

. To delete the class files and other build artifacts, go back to the *Projects* tab, right-click the project, and select *Clean*.

==== To Undeploy the hello1 Web Module Using Maven

To undeploy the `hello1` web module using Maven:

. In a terminal window, go to:
+
----
tut-install/examples/web/faces/hello1/
----

. Enter the following command:
+
[source,shell]
----
mvn cargo:undeploy
----

. To delete the class files and other build artifacts, enter the following command:
+
[source,shell]
----
mvn clean
----
