== Hello World Web Application Using Jakarta Faces

The `hello-faces` application is a web application that uses Jakarta Faces take a name as an HTTP request parameter, generate the greeting and return it as an HTTP response.
As a presentation-oriented web application, the response is represented as a HTML document.

The source code for this application is in the `_tut-install_/tutorial/web/faces/hello-faces/` directory.

Jakarta Faces is a component based MVC framework that provides its own servlet as controller (the "C" part of MVC), the `FacesServlet`.
The model and the view are usually provided by you, the web developer.

=== The Model

In a typical Jakarta Faces application, the model (the "M" part of MVC) is represented by a JavaBean class.
Such a JavaBean class is in the Jakarta Faces world called a _Backing Bean_.

For this Hello World web application, the `src/main/java/jakarta/tutorial/faces/Hello.java` backing bean defines a `name` property along with a getter and setter, a `greeting` property along with a getter, and a `submit` action method which creates the `greeting` as output based on `name` as input.

[source,java]
----
package jakarta.tutorial.web.faces;

import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Named;

@Named
@RequestScoped
public class Hello {

    private String name;
    private String greeting;

    public void submit() {
        greeting = "Hello, " + name + "!";
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public String getGreeting() {
        return greeting;
    }
}
----

Note that a getter is required for output and that a setter is only required for input.

In a typical Jakarta Faces application, CDI is used to manage the backing beans.
We'll briefly go through the CDI annotations that are used here:

* `@Named` -- gives the backing bean a managed bean name, which is primarily used to reference it in Expression Language (EL).
  Without any attributes this defaults to the simple class name with the first letter in lowercase.
  This backing bean will thus be available as a managed bean via `#{hello}` in EL.
* `@RequestScoped` -- gives the backing bean a managed bean scope, which essentially represents its lifespan.
  In this case that lifespan is the duration of an HTTP request.
  When the HTTP request ends, then the managed bean instance is destroyed.

=== The View

In a typical Jakarta Faces application, the view (the "V" part of MVC) is represented by a XHTML file.
Such a XHTML file is in the Jakarta Faces world called a _Facelets File_ or just _Facelet_.
In Jakarta Faces, the view technology is pluggable and Facelets is used as the default view technology.
XHTML markup is being used because it allows the framework to easily use a XML parser to find Jakarta Faces tags of interest and to generate HTML output.

For this Hello World web application, the `src/main/webapp/hello.xhtml` Facelet defines a form with an input field, a command button and an output field:

[source,xml]
----
<!DOCTYPE html>
<html lang="en"
      xmlns:f="jakarta.faces.core"
      xmlns:h="jakarta.faces.html">
    <h:head>
        <title>Jakarta Faces Hello World</title>
    </h:head>
    <h:body>
        <h1>Hello, what's your name?</h1>
        <h:form>
            <h:inputText value="#{hello.name}" required="true" />
            <h:commandButton value="Submit" action="#{hello.submit}">
                <f:ajax execute="@form" render=":greeting" />
            </h:commandButton>
            <h:messages />
        </h:form>
        <h:outputText id="greeting" value="#{hello.greeting}" />
    </h:body>
</html>
----

We'll briefly go through the Jakarta Faces-specific XHTML tags that are used here.

* `<h:head>` -- generates the HTML `<head>`.
  It gives Jakarta Faces the opportunity to automatically include any necessary JS and CSS files in the generated HTML head.
* `<h:body>` -- generates the HTML `<body>`.
  It gives Jakarta Faces the opportunity to automatically include any necessary JS files in the end of the generated HTML body.
* `<h:form>` -- generates the HTML `<form>`.
  It gives Jakarta Faces the opportunity to automatically include a hidden field representing the view state.
* `<h:inputText>` -- generates the HTML `<input>`.
  It gives Jakarta Faces the opportunity to automatically get and set the value as a managed bean property specified in the `value` attribute, as well as to perform any conversion and validation on it.
* `<h:commandButton>` -- generates the HTML `<input type="submit">`.
  It gives Jakarta Faces the opportunity to automatically invoke the backing bean method specified in the `action` attribute.
* `<h:messages>` -- generates the HTML `<ul>` or `<div>` or `<table>` depending on state and configuration.
  It gives you the opportunity to declare the place where any conversion and validation messages will be displayed.
* `<f:ajax>` -- generates the necessary JavaScript code for Ajax behavior.
  If gives you the opportunity to configure the form submit to be performed asynchronously using Ajax.
* `<h:outputText>` -- generates the HTML `<span>`.
  This is the one being updated on completion of the Ajax submit and it will display the current value of the managed bean property specified in the `value` attribute.

The `<h:...>` tags basically define standard HTML components.
The `<f:...>` tags basically define behavior.

The input value is via EL value expression `#{hello.name}` connected to the `name` property of the `Hello` backing bean via its getter and setter.
The output value is via EL value expression `#{hello.greeting}` connected to the `greeting` property of the `Hello` backing bean via its getter.
The command button is via EL method expression `#{hello.submit}` connected to the `submit` method of the `Hello` backing bean.

Note that for EL value expressions the physical field representing the property doesn't need to have exactly the same name nor that it needs to exist at all.
EL only looks for the getter and setter methods, not for the field.

=== The Controller

In a typical Jakarta Faces application, the controller (the "C" part of MVC) is registered in the Jakarta Servlet deployment descriptor file, the `src/main/webapp/WEB-INF/web.xml`.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_6_0.xsd"
         version="6.0">
    <servlet>
        <servlet-name>facesServlet</servlet-name>
        <servlet-class>jakarta.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>facesServlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>
</web-app>
----

It basically instructs the servlet container to create an instance of `jakarta.faces.webapp.FacesServlet` as `facesServlet` during startup and to execute it when the URL pattern of the HTTP request matches `*.xhtml`.









=== Packaging and Deploying the hello1 Web Module

A web module must be packaged into a WAR in certain deployment scenarios and whenever you want to distribute the web module.
You can package a web module into a WAR file by using Maven or by using the IDE tool of your choice.
This tutorial shows you how to use NetBeans IDE or Maven to build, package, and deploy the `hello1` sample application.

You can deploy a WAR file to GlassFish Server by:

* Using NetBeans IDE

* Using the `asadmin` command

* Using the Administration Console

* Copying the WAR file into the `_domain-dir_/autodeploy/` directory

Throughout the tutorial, you will use NetBeans IDE or Maven for packaging and deploying.

==== To Build, Package and Deploy the hello1 Web Module Using NetBeans IDE

To build and package the `hello1` web module using NetBeans IDE:

. Start GlassFish Server as described in <<to-start-glassfish-server-using-netbeans-ide>>, if you have not already done so.

. From the *File* menu, choose *Open Project*.

. In the Open Project dialog box, navigate to:
+
----
tut-install/examples/web/faces
----

. Select the `hello1` folder.

. Click *Open Project*.

. In the *Projects* tab, right-click the `hello1` project and select *Build*. This command deploys the project to the server.

==== To Build, Package and Deploy the hello1 Web Module Using Maven

To build and package the `hello1` web module using Maven:

. Start GlassFish Server as described in <<to-start-glassfish-server-using-the-command-line>>, if you have not already done so.

. In a terminal window, go to:
+
----
tut-install/examples/web/faces/hello1/
----

. Enter the following command:
+
[source,shell]
----
mvn install
----
+
This command spawns any necessary compilations and creates the WAR file in `_tut-install_/examples/web/faces/hello1/target/`.
It then deploys the project to the server.

=== Viewing Deployed Web Modules

GlassFish Server provides two ways to view the deployed web modules: the Administration Console and the `asadmin` command.
You can also use NetBeans IDE to view deployed modules.

==== To View Deployed Web Modules Using the Administration Console

To view deployed web modules using the Administration Console:

. Open the URL http://localhost:4848/[^] in a browser.

. Select the Applications node.
+
The deployed web modules appear in the Deployed Applications table.

==== To View Deployed Web Modules Using the asadmin Command

Enter the following command:

[source,shell]
----
asadmin list-applications
----

==== To View Deployed Web Modules Using NetBeans IDE

To view deployed web modules using NetBeans IDE:

. In the *Services* tab, expand the *Servers* node, then expand the *GlassFish Server* node.

. Expand the *Applications* node to view the deployed modules.

=== Running the Deployed hello1 Web Module

Now that the web module is deployed, you can view it by opening the application in a web browser.
By default, the application is deployed to host `localhost` on port 8080.
The context root of the web application is `hello1`.

To run the deployed `hello1` web module:

. Open a web browser.

. Enter the following URL:
+
----
http://localhost:8080/hello1/
----

. In the field, enter your name and click Submit.
+
The response page displays the name you submitted. Click Back to try again.

==== Dynamic Reloading of Deployed Modules

If dynamic reloading is enabled, you do not have to redeploy an application or module when you change its code or deployment descriptors.
All you have to do is copy the changed pages or class files into the deployment directory for the application or module.
The deployment directory for a web module named context-root is `_domain-dir_/applications/_context-root_`.
The server checks for changes periodically and redeploys the application, automatically and dynamically, with the changes.

This capability is useful in a development environment because it allows code changes to be tested quickly.
Dynamic reloading is not recommended for a production environment, however, because it may degrade performance.
In addition, whenever a reload takes place, the sessions at that time become invalid, and the client must restart the session.

In GlassFish Server, dynamic reloading is enabled by default.

=== Undeploying the hello1 Web Module

You can undeploy web modules and other types of enterprise applications by using either NetBeans IDE or Maven.

==== To Undeploy the hello1 Web Module Using NetBeans IDE

To undeploy the `hello1` web module using NetBeans IDE:

. In the *Services* tab, expand the *Servers* node, then expand the *GlassFish Server* node.

. Expand the *Applications* node.

. Right-click the `hello1` module and select *Undeploy*.

. To delete the class files and other build artifacts, go back to the *Projects* tab, right-click the project, and select *Clean*.

==== To Undeploy the hello1 Web Module Using Maven

To undeploy the `hello1` web module using Maven:

. In a terminal window, go to:
+
----
tut-install/examples/web/faces/hello1/
----

. Enter the following command:
+
[source,shell]
----
mvn cargo:undeploy
----

. To delete the class files and other build artifacts, enter the following command:
+
[source,shell]
----
mvn clean
----
