[[GKKNJ]][[using-jax-rs-with-jaxb]]

== Using Jakarta REST with Jakarta XML Binding

JAXB is an XML-to-Java binding
technology that simplifies the development of web services by enabling
transformations between schema and Java objects and between XML instance
documents and Java object instances. An XML schema defines the data
elements and structure of an XML document. You can use Jakarta XML Binding APIs and
tools to establish mappings between Java classes and XML schema. Jakarta XML Binding
technology provides the tools that enable you to convert your XML
documents to and from Java objects.

By using Jakarta XML Binding, you can manipulate data objects in the following ways.

* You can start with an XML schema definition (XSD) and use `xjc`, the
Jakarta XML Binding schema compiler tool, to create a set of Jakarta XML Binding annotated Java
classes that map to the elements and types defined in the XSD schema.
* You can start with a set of Java classes and use `schemagen`, the Jakarta XML Binding
schema generator tool, to generate an XML schema.
* Once a mapping between the XML schema and the Java classes exists, you
can use the Jakarta XML Binding runtime to marshal and unmarshal your XML
documents to and from Java objects and use the resulting Java classes to
assemble a web services application.

XML is a common media format that RESTful services consume and produce.
To deserialize and serialize XML, you can represent requests and
responses by Jakarta XML Binding annotated objects. Your Jakarta REST application can use the
Jakarta XML Binding objects to manipulate XML data. Jakarta XML Binding objects can be used as request
entity parameters and response entities. The Jakarta REST runtime environment
includes standard `MessageBodyReader` and `MessageBodyWriter` provider
interfaces for reading and writing Jakarta XML Binding objects as entities.

With Jakarta REST, you enable access to your services by publishing resources.
Resources are just simple Java classes with some additional Jakarta REST
annotations. These annotations express the following:

* The path of the resource (the URL you use to access it)
* The HTTP method you use to call a certain method (for example, the
`GET` or `POST` method)
* The MIME type with which a method accepts or responds

As you define the resources for your application, consider the type of
data you want to expose. You may already have a relational database that
contains information you want to expose to users, or you may have static
content that does not reside in a database but does need to be
distributed as resources. Using Jakarta REST, you can distribute content from
multiple sources. RESTful web services can use various types of
input/output formats for request and response. The `customer` example,
described in link:#GKOIB[The customer Example
Application], uses XML.

Resources have representations. A resource representation is the content
in the HTTP message that is sent to, or returned from, the resource
using the URI. Each representation a resource supports has a
corresponding media type. For example, if a resource is going to return
content formatted as XML, you can use `application/xml` as the
associated media type in the HTTP message.Depending on the requirements
of your application, resources can return representations in a preferred
single format or in multiple formats. Jakarta REST provides `@Consumes` and
`@Produces` annotations to declare the media types that are acceptable
for a resource method to read and write.

Jakarta REST also maps Java types to and from resource representations using
entity providers. A `MessageBodyReader` entity provider reads a request
entity and deserializes the request entity into a Java type. A
`MessageBodyWriter` entity provider serializes from a Java type into a
response entity. For example, if a `String` value is used as the request
entity parameter, the `MessageBodyReader` entity provider deserializes
the request body into a new `String`. If a Jakarta XML Binding type is used as the
return type on a resource method, the `MessageBodyWriter` serializes the
Jakarta XML Binding object into a response body.

By default, the Jakarta REST runtime environment attempts to create and use a
default `JAXBContext` class for Jakarta XML Binding classes. However, if the default
`JAXBContext` class is not suitable, then you can supply a `JAXBContext`
class for the application using a Jakarta REST `ContextResolver` provider
interface.

The following sections explain how to use Jakarta XML Binding with Jakarta REST resource
methods.

[[sthref147]][[using-java-objects-to-model-your-data]]

=== Using Java Objects to Model Your Data

If you do not have an XML schema definition for the data you want to
expose, you can model your data as Java classes, add Jakarta XML Binding annotations to
these classes, and use Jakarta XML Binding to generate an XML schema for your data. For
example, if the data you want to expose is a collection of products and
each product has an ID, a name, a description, and a price, you can
model it as a Java class as follows:

[source,java]
----
@XmlRootElement(name="product")
@XmlAccessorType(XmlAccessType.FIELD)
public class Product {

    @XmlElement(required=true)
    protected int id;
    @XmlElement(required=true)
    protected String name;
    @XmlElement(required=true)
    protected String description;
    @XmlElement(required=true)
    protected int price;

    public Product() {}

    // Getter and setter methods
    // ...
}
----

Run the Jakarta XML Binding schema generator on the command line to generate the
corresponding XML schema definition:

[source,java]
----
schemagen Product.java
----

This command produces the XML schema as an `.xsd` file:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="product" type="product"/>

    <xs:complexType name="product">
      <xs:sequence>
        <xs:element name="id" type="xs:int"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="price" type="xs:int"/>
      </xs:sequence>
    <xs:complexType>
</xs:schema>
----

Once you have this mapping, you can create `Product` objects in your
application, return them, and use them as parameters in Jakarta REST resource
methods. The Jakarta REST runtime uses Jakarta XML Binding to convert the XML data from the
request into a `Product` object and to convert a `Product` object into
XML data for the response. The following resource class provides a
simple example:

[source,java]
----
@Path("/product")
public class ProductService {
    @GET
    @Path("/get")
    @Produces("application/xml")
    public Product getProduct() {
        Product prod = new Product();
        prod.setId(1);
        prod.setName("Mattress");
        prod.setDescription("Queen size mattress");
        prod.setPrice(500);
        return prod;
    }

    @POST
    @Path("/create")
    @Consumes("application/xml")
    public Response createProduct(Product prod) {
        // Process or store the product and return a response
        // ...
    }
}
----

Some IDEs, such as NetBeans IDE, will run the schema generator tool
automatically during the build process if you add Java classes that have
Jakarta XML Binding annotations to your project. For a detailed example, see
link:#GKOIB[The customer Example Application]. The
`customer` example contains a more complex relationship between the Java
classes that model the data, which results in a more hierarchical XML
representation.

[[sthref148]][[starting-from-an-existing-xml-schema-definition]]

=== Starting from an Existing XML Schema Definition

If you already have an XML schema definition in an `.xsd` file for the
data you want to expose, use the Jakarta XML Binding schema compiler tool. Consider
this simple example of an `.xsd` file:

[source,xml]
----
<xs:schema targetNamespace="http://xml.product"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns:myco="http://xml.product">
  <xs:element name="product" type="myco:Product"/>
  <xs:complexType name="Product">
    <xs:sequence>
      <xs:element name="id" type="xs:int"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="price" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
----

Run the schema compiler tool on the command line as follows:

[source,java]
----
xjc Product.xsd
----

This command generates the source code for Java classes that correspond
to the types defined in the `.xsd` file. The schema compiler tool
generates a Java class for each `complexType` defined in the `.xsd`
file. The fields of each generated Java class are the same as the
elements inside the corresponding `complexType`, and the class contains
getter and setter methods for these fields.

In this case, the schema compiler tool generates the classes
`product.xml.Product` and `product.xml.ObjectFactory`. The `Product`
class contains Jakarta XML Binding annotations, and its fields correspond to those in
the `.xsd` definition:

[source,java]
----
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "id",
    "name",
    "description",
    "price"
})
public class Product {
    protected int id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    protected int price;

    // Setter and getter methods
    // ...
}
----

You can create instances of the `Product` class from your application
(for example, from a database). The generated class
`product.xml.ObjectFactory` contains a method that allows you to convert
these objects to Jakarta XML Binding elements that can be returned as XML inside Jakarta REST
resource methods:

[source,java]
----
@XmlElementDecl(namespace = "http://xml.product", name = "product")
public JAXBElement<Product> createProduct(Product value) {
    return new JAXBElement<Product>(_Product_QNAME, Product.class, null, value);
}
----

The following code shows how to use the generated classes to return a
Jakarta XML Binding element as XML in a Jakarta REST resource method:

[source,java]
----
@Path("/product")
public class ProductService {
    @GET
    @Path("/get")
    @Produces("application/xml")
    public JAXBElement<Product> getProduct() {
        Product prod = new Product();
        prod.setId(1);
        prod.setName("Mattress");
        prod.setDescription("Queen size mattress");
        prod.setPrice(500);
        return new ObjectFactory().createProduct(prod);
    }
}
----

For `@POST` and `@PUT` resource methods, you can use a `Product` object
directly as a parameter. Jakarta REST maps the XML data from the request into
a `Product` object.

[source,java]
----
@Path("/product")
public class ProductService {
    @GET
    // ...

    @POST
    @Path("/create")
    @Consumes("application/xml")
    public Response createProduct(Product prod) {
        // Process or store the product and return a response
        // ...
    }
}
----

[[sthref149]][[using-json-with-jax-rs-and-jaxb]]

=== Using JSON with Jakarta REST and Jakarta XML Binding

Jakarta REST can automatically read and write XML using Jakarta XML Binding, but it can also
work with JSON data. JSON is a simple text-based format for data
exchange derived from JavaScript. For the preceding examples, the XML
representation of a product is

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<product>
  <id>1</id>
  <name>Mattress</name>
  <description>Queen size mattress</description>
  <price>500</price>
</product>
----

The equivalent JSON representation is

[source,json]
----
{
    "id":"1",
    "name":"Mattress",
    "description":"Queen size mattress",
    "price":500
}
----

You can add the format `application/json` or
`MediaType.APPLICATION_JSON` to the `@Produces` annotation in resource
methods to produce responses with JSON data:

[source,java]
----
@GET
@Path("/get")
@Produces({"application/xml","application/json"})
public Product getProduct() { ... }
----

In this example, the default response is XML, but the response is a JSON
object if the client makes a `GET` request that includes this header:

[source,java]
----
Accept: application/json
----

The resource methods can also accept JSON data for Jakarta XML Binding annotated
classes:

[source,java]
----
@POST
@Path("/create")
@Consumes({"application/xml","application/json"})
public Response createProduct(Product prod) { ... }
----

The client should include the following header when submitting JSON data
with a `POST` request:

[source,java]
----
Content-Type: application/json
----


