Jakarta REST: Advanced Topics and an Example
============================================

[[GJJXE]][[jax-rs-advanced-topics-and-an-example]]

34 Jakarta REST: Advanced Topics and an Example
-----------------------------------------------


Jakarta RESTful Web Services (Jakarta REST) is
designed to make it easy to develop applications that use the REST
architecture. This chapter describes advanced features of Jakarta REST. If you
are new to Jakarta REST, see link:jaxrs.html#GIEPU[Chapter 32, "Building
RESTful Web Services with Jakarta REST"] before you proceed with this chapter.

Jakarta REST is integrated with Jakarta Contexts and Dependency Injection
(CDI), Jakarta Enterprise Beans technology, and Jakarta Servlet
technology.

The following topics are addressed here:

* link:jaxrs-advanced001.html#GKKRB[Annotations for Field and Bean
Properties of Resource Classes]
* link:jaxrs-advanced002.html#BABCJEDF[Validating Resource Data with Bean
Validation]
* link:jaxrs-advanced003.html#GKNAV[Subresources and Runtime Resource
Resolution]
* link:jaxrs-advanced004.html#GKNCY[Integrating Jakarta REST with Jakarta Enterprise Beans
Technology and CDI]
* link:jaxrs-advanced005.html#GKQDA[Conditional HTTP Requests]
* link:jaxrs-advanced006.html#GKQBQ[Runtime Content Negotiation]
* link:jaxrs-advanced007.html#GKKNJ[Using Jakarta REST with Jakarta XML Binding]
* link:jaxrs-advanced008.html#GKOIB[The customer Example Application]
