== Implementing an Event Listener

The Jakarta Server Faces technology supports action events and
value-change events for components.

Action events occur when the user activates a component that implements
`jakarta.faces.component.ActionSource`. These events are represented by
the class `jakarta.faces.event.ActionEvent`.

Value-change events occur when the user changes the value of a
component that implements
`jakarta.faces.component.EditableValueHolder`. These events are
represented by the class `jakarta.faces.event.ValueChangeEvent`.

One way to handle events is to implement the appropriate listener
classes. Listener classes that handle the action events in an
application must implement the interface
`jakarta.faces.event.ActionListener`. Similarly, listeners that handle
the value-change events must implement the interface
`jakarta.faces.event.ValueChangeListener`.

This section explains how to implement the two listener classes.

To handle events generated by custom components, you must implement an
event listener and an event handler and manually queue the event on the
component. See <<handling-events-for-custom-components>> for more
information.

[NOTE]
You do not need to create an `ActionListener` implementation to handle
an event that results solely in navigating to a page and does not
perform any other application-specific processing. See
<<writing-a-method-to-handle-navigation>> for information on how to
manage page navigation.


=== Implementing Value-Change Listeners

A `jakarta.faces.event.ValueChangeListener` implementation must include
a `processValueChange(ValueChangeEvent)` method. This method processes
the specified value-change event and is invoked by the Jakarta Server
Faces implementation when the value-change event occurs. The
`ValueChangeEvent` instance stores the old and the new values of the
component that fired the event.

In the Duke's Bookstore case study, the `NameChanged` listener
implementation is registered on the `name` `UIInput` component on the
`bookcashier.xhtml` page. This listener stores into session scope the
name the user entered in the field corresponding to the name component.

The `bookreceipt.xhtml` subsequently retrieves the name from the
session scope:

[source,xml]
----
<h:outputFormat title="thanks"
                value="#{bundle.ThankYouParam}">
    <f:param value="#{sessionScope.name}"/>
</h:outputFormat>
----

When the `bookreceipt.xhtml` page is loaded, it displays the name
inside the message:

[source,java]
----
"Thank you, {0}, for purchasing your books from us."
----

Here is part of the `NameChanged` listener implementation:

[source,java]
----
public class NameChanged extends Object implements ValueChangeListener {

    @Override
    public void processValueChange(ValueChangeEvent event)
            throws AbortProcessingException {
    
        if (null != event.getNewValue()) {
            FacesContext.getCurrentInstance().getExternalContext().
                getSessionMap().put("name", event.getNewValue());
        }
    }
}
----

When the user enters the name in the field, a value-change event is
generated, and the `processValueChange(ValueChangeEvent)` method of the
`NameChanged` listener implementation is invoked. This method first
gets the ID of the component that fired the event from the
`ValueChangeEvent` object, and it puts the value, along with an
attribute name, into the session map of the `FacesContext` instance.

<<registering-a-value-change-listener-on-a-component>> explains how to
register this listener onto a component.

=== Implementing Action Listeners

A `jakarta.faces.event.ActionListener` implementation must include a
`processAction(ActionEvent)` method. The `processAction(ActionEvent)`
method processes the specified action event. The Jakarta Server Faces
implementation invokes the `processAction(ActionEvent)` method when the
`ActionEvent` occurs.

The Duke's Bookstore case study uses two `ActionListener`
implementations, `LinkBookChangeListener` and `MapBookChangeListener`.
See <<handling-events-for-custom-components>> for details on
`MapBookChangeListener`.

<<registering-an-action-listener-on-a-component>> explains how to
register this listener onto a component.
