[[A1352824]][[_introduction_to_configuring_javaserver_faces_applications]]

== Introduction to Configuring Jakarta Server Faces Applications

The process of building and deploying simple Jakarta Server Faces
applications is described in earlier chapters of this tutorial,
including xref:webapp/webapp.adoc#BNADR[Chapter 6, "Getting Started with Web
Applications,"] xref:jsf-facelets/jsf-facelets.adoc#GIEPX[Chapter 8, "Introduction to
Facelets,"] xref:jsf-ajax/jsf-ajax.adoc#GKIOW[Chapter 13, "Using Ajax with
Jakarta Server Faces Technology,"] and
xref:jsf-advanced-cc/jsf-advanced-cc.adoc#GKHXA[Chapter 14, "Composite Components:
Advanced Topics and an Example."] When you create large and complex
applications, however, various additional configuration tasks are
required. These tasks include the following:

* Registering managed beans with the application so that all parts of
the application have access to them
* Configuring managed beans and model beans so that they are
instantiated with the proper values when a page makes reference to them
* Defining navigation rules for each of the pages in the application so
that the application has a smooth page flow, if nondefault navigation is
needed
* Packaging the application to include all the pages, resources, and
other files so that the application can be deployed on any compliant
container


